#+TITLE: Functional Analysis 1
#+LATEX_HEADER: \usepackage[left=2cm, right=2cm, bottom=2cm, top=2cm]{geometry}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \def\R{\mathbb{R}}
#+LATEX_HEADER: \def\Z{\mathbb{Z}}
#+LATEX_HEADER: \def\pos{\operatorname{pos}}
#+LATEX_HEADER: \def\conv{\operatorname{Conv}}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
* Lecture 2 <2018-10-17 Wed>

** Examples of metric spaces

*** The set of continuous functions $C[a, b]$
    With a metric $d(f, g) = \max\vert f(x) - g(x)\vert$

*** The space $l^p$ of sequences $x=(x_1, x_2 \cdots,)$ with $\Vert x \Vert _p < \infty$. 
    The metric is the norm of the difference. 

    To prove that this is indeed a metric, we need the Minkowiski inequality.

    There was a complicated proof of the Minkowski inequality that was discussed
    in the lecture. I think one can prove in a simpler fashion. 

    The proof involved showing that $\alpha \cdot \beta \le \alpha^{p}/p +
    \beta^{q}/q$ (This is the young inequality.)

    The next step was to prove the Holder inequality. 

    The next step is to use Holder on Minkowski. 

    Holder: [[https://en.wikipedia.org/wiki/H%C3%B6lder%27s_inequality]]

    Minkowski: [[https://en.wikipedia.org/wiki/Minkowski_inequality]]

    For $p=q=2$, we obtain the Cauchy-Schwarz inequality. 

** Definitions involving metric spaces

*** Open ball
    $B(x_0, r)$ is the set of all points $x$ such that the distance from $x$ to $x_0$ is less than $r$.

*** Closed ball
    Similar to open ball, except that the distance can be less than or /equal to/ $r$.

*** Sphere
    The set of all points $x$ such that the distance from $x_0$ to $x$ is exactly $r$.

*** Relation
    If we subtract a sphere from the closed ball, we get the open ball.

*** Definition of open
    For every point $x$, we can find an epsilon ball that is inside the set. 

*** Definition of closed
    Basically the complement of the set is open.

*** Remark ($\varepsilon$ neighbourhood)
    An open ball $B(x_0, \verepsilon)$ of radius $\varepsilon$ is often called
    an $\varepsilon$ neighbourhood. A neighbourhood of $X$ is that contains an
    $\varepsilon$ neighbourhood of $X$

    We will use these definition for separable spaces.

*** Interior point 
    We call $x_0$ an interior point if there exist an neighbourhood of $x_0$
    contained inside the space.

*** Continuity
    About a function from one metric space to another. It's basically the
    standard definition. (the definition in the lecture was an $\varepsilon$,
    $\delta$ definition.) 

    The definition was about continuity at a point $x$. Then a function is
    defined to be continuous if it is continuous at every point $x$.

*** Accumulation point
    $A$ be a subset of $X$. Then $x_0 \in X$ (not necessarily in $A$) is called
    accumulation point of $A$ if every neighbourhood of $X_0$ contains at least
    one point $y \in A$, $y \neq x_0$.

* Lecture 3 <2018-10-23 Tue>
  [fn:1]
** More definitions
*** Closure of a set
*** A dense subset of $X$
*** Separable
    If there is a countable subset that is dense in $X$. $X$ is defined to be
    separable.

    Example:
    1. Real numbers are separable.
    2. $l^p$ for $1 \le p \le \infty$ is separable.
    3. $l^\infty$ not separable. Proof idea: For any set of indices $I\subset
       \N$, define $(e_I)_n$ is $1$ is $h\in I$ and $0$ otherwise. For every $I
       \neq y$, we can compute the distance $d(e_I, e_J) = 1$. How many such
       functions are there? The number of such elements are uncountable. (The
       proof of this theorem is similar to how $\{0, 1\}^\N$ is uncountable.)[fn:2]
*** Definition of convergence
    Definition was about the limit of distance going to 0. Note that the limit
    $X$ must be a point in $X$ (Why?)
*** Definition of bounded set
*** Definition of boundedness of a sequence
*** Lemma
    If $x_n$ is convergent, then it is bounded the limit is unique.
*** Lemma
    If $x_n$ converges to $x$ and $y_n$ converges to $y$, then $d(x_n, y_n)$
    converges to $d(x, y)$.
*** About convergence and Cauchy sequences
*** Completeness
    The idea that if a sequence is Cauchy, then it is convergent.
*** Theorem about subsets of complete metric space
    $X$ be a metric space. A subspace $A$ of $X$ is complete if and only if $A$ is closed in $X$.
*** Condition about continuity with respect to convergence
    A map $T\colon X \rightarrow Y$ is continuous if and only if $x_n
    \rightarrow x_0 \implies T(x_n) \rightarrow T(x_0)$.
*** Definition of isometry between metric spaces
** Theorem: $C[a, b]$ is complete
   Given a closed interval $[a, b]$, the $C[a, b]$ is complete. 
*** Proof
    Given a Cauchy sequence in this space. We use the completeness of $\R$ to
    define a function to which the Cauchy sequence will converge to. We need
    uniform convergence here.
** The set of polynomials on a $[a, b]$ is not complete
   $p_n(x) = \sum_i \left(\frac{x}{2}\right)^i$. 

* Lecture 4 <2018-10-25 Thu>
** Clarification
   Some sources say that an Isometry need not be surjective. 

   Let $T\colon X \rightarrow Y$ be injective and $d(x, y) = \tilde{d}(Tx, Ty)
   \forall x, y \in X$.

   Then $T$ is called isometry (from $X$) into $Y$. 

   A couple of examples of isometry were discussed. 

   Also we talked about uniform convergence, and also an example of a sequence
   that is not uniformly convergent was also discussed. (The idea is that on a
   compact set [fn:3], if a uniformly convergent function converges to a
   function is continuous.)

   Recall that we have already shown that $C[0, 1]$ is a complete space, meaning
   that if a sequence is Cauchy, then it has a limit in the space. Which means
   that the limit must also be continuous. (Kinda similar to how uniform
   convergence works.)
** Normed spaces and Banach spaces
   A Banach space is just a complete normed space.
*** Norm
    A metric space can be obtained by equipping a vector space with a metric
    defined in terms of the union, resulting in the *normed space*. Complete
    normed spaces are called *Banach space*.

    A mapping from one normed space to another is called an *operator* ($T\colon
    X \rightarrow Y). A mapping from a normed space to $\R$ is called a
    *functional* ($T\colon X \rightarrow \R$)

    It can be shown that a linear operator is continuous if and only if it is
    bounded.

    The set of all bounded linear operators from a space $X$ to a space $Y$ is
    again a normed space.

    Similarly, the set of all bounded linear functionals is a normed space, the
    dual space $X'$ of $X$.
*** Vector space
    I didn't write this down. But it's pretty clear. 
*** Examples
    1. $\R^n$
    2. $C[a, b]$. It's kinda clear how to define a vector space structure on it. 
*** Subspace
    We defined a subspace of a vector space. 
*** Span
    Span was defined.
*** Linear independence
*** Definition of dimension
*** Basis of space
    To construct basis for finite dimensional spaces are clear. 

    One can prove the existence of a basis for infinite dimensional spaces, but
    the proof is not constructive.
** Normed spaces
*** Definition of a norm
*** Examples
    1. $\R^n$
    2. $C[a, b]$ with $\Vert f \Vert$ with $\Vert f\Vert = \max_{x \in [a, b]}
       \vert f (x) \vert$. Is also a Banach space.
    3. $\Omega \in \R^n$ be a measurable set, then the space $L^p(\Omega)$ is
       the set of all Lebesgue measurable functions from $\Omega \rightarrow
       \R$. We can define the norm in a straightforward manner.

       We can show that this space is a Banach space.
* Footnotes

[fn:3] Is compactness needed?

[fn:2] Look up at proofs of this fact

[fn:1] A14 1126 tutorial

