#+TITLE: Functional Analysis 1
#+LATEX_HEADER: \usepackage[left=2cm, right=2cm, bottom=2cm, top=2cm]{geometry}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \def\R{\mathbb{R}}
#+LATEX_HEADER: \def\C{\mathbb{C}}
#+LATEX_HEADER: \def\N{\mathbb{N}}
#+LATEX_HEADER: \def\Z{\mathbb{Z}}
#+LATEX_HEADER: \def\Q{\mathbb{Q}}
#+LATEX_HEADER: \def\pos{\operatorname{pos}}
#+LATEX_HEADER: \def\conv{\operatorname{Conv}}
#+LATEX_HEADER: \def\sgn{\operatorname{sgn}}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
* Lecture 2 <2018-10-17 Wed>

** Examples of metric spaces

*** The set of continuous functions $C[a, b]$
    With a metric $d(f, g) = \max\vert f(x) - g(x)\vert$

*** The space $l^p$ of sequences $x=(x_1, x_2 \cdots,)$ with $\Vert x \Vert _p < \infty$. 
    The metric is the norm of the difference. 

    To prove that this is indeed a metric, we need the Minkowiski inequality.

    There was a complicated proof of the Minkowski inequality that was discussed
    in the lecture. I think one can prove in a simpler fashion. 

    The proof involved showing that $\alpha \cdot \beta \le \alpha^{p}/p +
    \beta^{q}/q$ (This is the young inequality.)

    The next step was to prove the Holder inequality. 

    The next step is to use Holder on Minkowski. 

    Holder: [[https://en.wikipedia.org/wiki/H%C3%B6lder%27s_inequality]]

    Minkowski: [[https://en.wikipedia.org/wiki/Minkowski_inequality]]

    For $p=q=2$, we obtain the Cauchy-Schwarz inequality. 

** Definitions involving metric spaces

*** Open ball
    $B(x_0, r)$ is the set of all points $x$ such that the distance from $x$ to $x_0$ is less than $r$.

*** Closed ball
    Similar to open ball, except that the distance can be less than or /equal to/ $r$.

*** Sphere
    The set of all points $x$ such that the distance from $x_0$ to $x$ is exactly $r$.

*** Relation
    If we subtract a sphere from the closed ball, we get the open ball.

*** Definition of open
    For every point $x$, we can find an epsilon ball that is inside the set. 

*** Definition of closed
    Basically the complement of the set is open.

*** Remark ($\varepsilon$ neighbourhood)
    An open ball $B(x_0, \varepsilon)$ of radius $\varepsilon$ is often called
    an $\varepsilon$ neighbourhood. A neighbourhood of $X$ is that contains an
    $\varepsilon$ neighbourhood of $X$

    We will use these definition for separable spaces.

*** Interior point 
    We call $x_0$ an interior point if there exist an neighbourhood of $x_0$
    contained inside the space.

*** Continuity
    About a function from one metric space to another. It's basically the
    standard definition. (the definition in the lecture was an $\varepsilon$,
    $\delta$ definition.) 

    The definition was about continuity at a point $x$. Then a function is
    defined to be continuous if it is continuous at every point $x$.

*** Accumulation point
    $A$ be a subset of $X$. Then $x_0 \in X$ (not necessarily in $A$) is called
    accumulation point of $A$ if every neighbourhood of $X_0$ contains at least
    one point $y \in A$, $y \neq x_0$.

* Lecture 3 <2018-10-23 Tue>
  [fn:1]
** More definitions
*** Closure of a set
*** A dense subset of $X$
*** Separable
    If there is a countable subset that is dense in $X$. $X$ is defined to be
    separable.

    Example:
    1. Real numbers are separable.
    2. $l^p$ for $1 \le p \le \infty$ is separable.
    3. $l^\infty$ not separable. Proof idea: For any set of indices $I\subset
       \N$, define $(e_I)_n$ is $1$ is $h\in I$ and $0$ otherwise. For every $I
       \neq y$, we can compute the distance $d(e_I, e_J) = 1$. How many such
       functions are there? The number of such elements are uncountable. (The
       proof of this theorem is similar to how $\{0, 1\}^\N$ is uncountable.)[fn:2]
*** Definition of convergence
    Definition was about the limit of distance going to 0. Note that the limit
    $X$ must be a point in $X$ (Why?)
*** Definition of bounded set
*** Definition of boundedness of a sequence
*** Lemma
    If $x_n$ is convergent, then it is bounded the limit is unique.
*** Lemma
    If $x_n$ converges to $x$ and $y_n$ converges to $y$, then $d(x_n, y_n)$
    converges to $d(x, y)$.
*** About convergence and Cauchy sequences
*** Completeness
    The idea that if a sequence is Cauchy, then it is convergent.
*** Theorem about subsets of complete metric space
    $X$ be a metric space. A subspace $A$ of $X$ is complete if and only if $A$ is closed in $X$.
*** Condition about continuity with respect to convergence
    A map $T\colon X \rightarrow Y$ is continuous if and only if $x_n
    \rightarrow x_0 \implies T(x_n) \rightarrow T(x_0)$.
*** Definition of isometry between metric spaces
** Theorem: $C[a, b]$ is complete
   Given a closed interval $[a, b]$, the $C[a, b]$ is complete. 
*** Proof
    Given a Cauchy sequence in this space. We use the completeness of $\R$ to
    define a function to which the Cauchy sequence will converge to. We need
    uniform convergence here.
** The set of polynomials on a $[a, b]$ is not complete
   $p_n(x) = \sum_i \left(\frac{x}{2}\right)^i$. 

* Lecture 4 <2018-10-25 Thu>
** Clarification
   Some sources say that an Isometry need not be surjective. 

   Let $T\colon X \rightarrow Y$ be injective and $d(x, y) = \tilde{d}(Tx, Ty)
   \forall x, y \in X$.

   Then $T$ is called isometry (from $X$) into $Y$. 

   A couple of examples of isometry were discussed. 

   Also we talked about uniform convergence, and also an example of a sequence
   that is not uniformly convergent was also discussed. (The idea is that on a
   compact set [fn:3], if a uniformly convergent function converges to a
   function is continuous.)

   Recall that we have already shown that $C[0, 1]$ is a complete space, meaning
   that if a sequence is Cauchy, then it has a limit in the space. Which means
   that the limit must also be continuous. (Kinda similar to how uniform
   convergence works.)
** Normed spaces and Banach spaces
   A Banach space is just a complete normed space.
*** Norm
    A metric space can be obtained by equipping a vector space with a metric
    defined in terms of the union, resulting in the *normed space*. Complete
    normed spaces are called *Banach space*.

    A mapping from one normed space to another is called an *operator* ($T\colon
    X \rightarrow Y). A mapping from a normed space to $\R$ is called a
    *functional* ($T\colon X \rightarrow \R$)

    It can be shown that a linear operator is continuous if and only if it is
    bounded.

    The set of all bounded linear operators from a space $X$ to a space $Y$ is
    again a normed space.

    Similarly, the set of all bounded linear functionals is a normed space, the
    dual space $X'$ of $X$.
*** Vector space
    I didn't write this down. But it's pretty clear. 
*** Examples
    1. $\R^n$
    2. $C[a, b]$. It's kinda clear how to define a vector space structure on it. 
*** Subspace
    We defined a subspace of a vector space. 
*** Span
    Span was defined.
*** Linear independence
*** Definition of dimension
*** Basis of space
    To construct basis for finite dimensional spaces are clear. 

    One can prove the existence of a basis for infinite dimensional spaces, but
    the proof is not constructive.
** Normed spaces
*** Definition of a norm
*** Examples
    1. $\R^n$
    2. $C[a, b]$ with $\Vert f \Vert$ with $\Vert f\Vert = \max_{x \in [a, b]}
       \vert f (x) \vert$. Is also a Banach space.
    3. $\Omega \in \R^n$ be a measurable set, then the space $L^p(\Omega)$ is
       the set of all Lebesgue measurable functions from $\Omega \rightarrow
       \R$. We can define the norm in a straightforward manner.

       We can show that this space is a Banach space.
* Lecture 5 <2018-10-30 Tue>
** Remark
   Not every metric is induced by a norm.

   Assume discrete metric is induced by a norm, i.e., $d(x, y) = \Vert x -
   y\Vert$. The proof is easy.
** Convergence of sequences in normed spaces
   1. A sequence $(x_n)$ in a normed space $X$ is convergent if there is an $x\in
      X$ with $\lim_{n\rightarrow \infty} \Vert x_n - x\Vert = 0$. We write again
      $\lim_{n\rightarrow \infty} x_n = x$.
   2. A sequence is called a cauchy sequence if for all $\epsilon > 0$, there
      exists $N$, $\Vert x_m - x_m \Vert < \epsilon$ for all $m, n > N$. [fn:4]
** Absolute convergence
   A series $S$ is called absolutely convergent if $\sum \Vert x_i \Vert$
   converges. If $X$ is complete, absolute convergence implies convergence.

   Example 1. The alternating sum $\sum (-1)^n/n$ is convergent, but not
   absolutely convergent. This converges to $-ln(2)$.

   Example 2. $X = \Q$, $a_n = \sum \left(\frac{1}{2^{i}} -
   \frac1{(i+1)!}\right)$. The first part converges to $1$. The second element
   converges to $e-2$. The total is $3-e$. Let $b_n$ be $\sum
   \frac{-1}{(i+1)!}$. This converges to $2 - e$. Now $a + b = 5 - 2e$. $a - b =
   1$. One of them converges to an element in $\Q$ whereas the other one does
   not convert to an element in $\Q$. Now we construct a new sequence with one
   element from the first one and the next element from the second one and
   continue doing this $(a_1, b_1, a_2, b_2, \cdots)$. $S_n$ will be the partial
   sums. Then $\sum x_i$ converges to $a+b$, but $\sum \vert x_i \vert $
   converges to $a - b = 1$.
** Definition of basis
   We can now define a basis as follows: Assume that the normed space $X$
   contains a sequence $(e_n)_n$. Such that every $x \in X$ in the normed space
   $X$, can be expressed in terms of $(e_n)_n$, i.e., every $x$ can be expressed
   as a weighted combination or linear sums of $(e_n)_n$. $\Vert x - \sum
   \alpha_i e_i \Vert \rightarrow 0$ as $n \rightarrow \infty$ and this
   expansion is also unique.

   If such a basis exists, then $X$ is separable.
** Theorem about completeness
   Every finite dimensional subspace $Y$ of a complete normed space $X$ is
   complete, which implies that all finite dimensional normed spaces are
   complete. [fn:5]
** Norm equivalence
   We have two norms. We want to say when two norms are equivalent.

   A norm $\Vert \Vert_1$ on $X$ is said to be equivalent to a norm $\Vert
   \Vert_2$ if there exists $a, b > 0$ such that

   $a \Vert x \vert_1 \le \Vert x \vert_2 \le b \Vert x \Vert_2$.

   An example: For finite-dimension vector space, then all norms are equivalent.

   We'll show that $\Vert \Vert_2$, and $\Vert \Vert_\infty$ are equivalent.

   Given any $X \in \R^n$, $\Vert x\Vert_2^2 = \sum_{i=1}^{n} x_i^2 \ge \max_i
   x_i^2 = \Vert x\Vert_\infty$. Also $\Vert x \Vert_2^2 = \sum_{i=1}^{n} x_i^2
   \le n \cdot \max x_i^2 = n \Vert x \Vert_\infty$. Thus $\Vert x \Vert_\infty
   \le \Vert x\Vert_2 \le \sqrt{n}\Vert x \Vert_\infty$.

   *A non-example*: Consider $X = C[0, 1]$ and define $f_n(X) = X^n$. Clearly,
   $f_n \in C[0, 1]$ for al l$n$.

   $\Vert f_n \Vert_\infty = \max_{x\in [0, 1]} \vert f_n(x)\vert$. Now we
   introduce another norm which is the Lebesgue integral. For $f_n$, this would
   evaluate to $1/{n+1}$. The contradiction is the fact that the maximal norm
   would be $1$ always, whereas, the Lebesgue norm would tend to $0$ as
   $n\rightarrow \infty$. There is a clear contradiction here.
** Compactness in metric spaces
   A metric space is defined to be compact if every sequence in $X$ has a
   convergent subsequence. A subset $M$ of $X$ is defined to be compact if $M$
   considered as a subspace is compact, i.e., every sequence has a convergent
   subsequence and the limit is in $M$.
** Theorem
   If $X$ is a fininte-dimensional normed space, then any subset $M \subset X$
   is compact if and only if $M is closed and bounded.

   Consider the sequence $\{x_n\}$ with $x_n = (-1)^n$, then $(x_n)$ does not
   converge, but it has convergent subsequences.
** Bolzano-Weistrass theorem
   Any bounded sequence $(x_n) \in l^{\infty}$ has a convergent subsequence.
*** Proof
    Without loss of generality, we assume that all elements are with $[0, 1]$,
    otherwise we an shift it and normalize it (can we do this?) Divide the
    interval $\{0, 1/2\}$ and $\{1/2, 1\}$, then one of them must have
    infinitely many points. (We can repeat the argument), we have a new sequence
    which are elements of $x_n$ that are in the interval (the interval with
    infinitely many points.) We can repeat this process again and the length of
    the intervals go to zero. It is clear how to construct a convergent
    subsequence.
*** Extension to bounded sub-sequences in $\R^n$.
* Lecture 5 <2018-11-01 Thu>
** Review
   In $\R^n$, the compact subsets are the closed and bounded subsets so that
   close-ness and boundedness can be used to define compactness. This can only
   be used for finite dimensional cases.
** Riesz's lemma
   Given a normed space $X$ with a closed subspace $y$ and a subspace $z$ such
   that $y$ is a subset of $z$. Given any number $\theta\in (0, 1)$, there
   exists, $z\in Z$ such that $\vert z \vert = 1$, and the distance $\Vert z - y
   \Vert \ge \theta$, for all $y \in Y$.
*** Proof
    Let $v\in Z \setminus Y$, define $a = \inf_{y \in Y} \Vert v - y\Vert$ to
    be the distance to $y$. Since $y$ is closed, $a>0$. Choose $\theta \in (0,
    1)$, then there exits a $y_0 \in y$, with $a \le \Vert v - y_0 \Vert \le
    \frac{a}{\theta}$.

    Define $z = \vert{1}{\Vert V = y_0}(V-y_0)$. Clearly, $\Vert z\Vert = 1$.
    Furthermore, given $y\in Y$, it holds that $\Vert z - y\Vert =
    \Vert\frac{1}{\Vert v - y_0\Vert}(v -y_0) - y\Vert = \frac{1}{\Vert v -
    y_0\Vert} \Vert v - y_0 - \Vert v-y_0\Vert\cdot y\Vert$.

    Since $Y$ is a subspace, $y_1 \in Y$ and $\Vert v - y_1\Vert \ge a$ (since a
    is the infimum.)

    $\Vert z - y\Vert = \frac{1}{\Vert v - y_0\Vert} \Vert V - y_1\Vert \le
    \frac{\theta}{a}a = \theta$
** Theorem 
   If the closed unit ball $M=\{X \vert \Vert X \Vert \le 1\}$ of a normed space
   $X$ is compact, then $X$ is finite-dimensional.

   The proof uses Riesz's lemma. Assume that $M$ is compact set but $\dim X =
   \infty$, this leads to a contradiction. Compact sets have compact images
   under continuous mappings.
** Theorem
   Suppose $X$ and $Y$ are metric spaces and $T \colon X \rightarrow X$ is
   continuous. Then any compact subset of $X$ is mapped to a compact subset of
   $Y$.
*** Proof
    Proof is easy.
** Corollary
   Given a continuous mapping $T \colon M \rightarrow \R$, where $M$ is a
   compact subset of $X$. Then $T$ assumes a maximum and a minimum at some
   points of $M$.
*** Proof
    The proof is easy. It's something like take the infimum, it has to be a
    point in the space because closed.
** Example
   The closed unit ball $M=\{f \colon \Vert f \Vert \le 1 \}$ of $C[0, 1]$ is
   not compact. To see this, define $f(X) = \max(1 - \vert X \vert, 0)$ and
   $f_n(X) = f(2n\cdot (n+1)(x - \frac{1}{n}))$ (functions with center $1/n$ and
   decreasing bandwidth converges to the zero function) [fn:6]

   Now $f_n \in C[0, 1]$ and $\Vert f_n \Vert_\infty = 1$. Since supports of $f_n$ do not overlap.

   $\Vert f_n f_m\Vert = \max_{X \in \{0, 1\}} \vert f_n(X) - f_m(X)\vert = 1$
   and the sequence does not have a convergent subsequence.
** Linear Operators
   We now consider linear operators and their properties.
*** Definition
    Let $T$ be an operator, $D(T)$ its domain and $R(T)$ its range. The operator
    is called linear if $T(x + y) = Tx+Ty$ and $T(\alpha x) = \alpha Tx$

    Note that we typically write $Tx$ and not $T(x)$ as it is done for functions.

    The null set $N(T)$ is defined $N(T) = \{x \in D(T) \colon Tx = 0\}$

    In particular, linearity implies $T0 = 0$.
*** Example
    Define $T$ by $(Tf)(x) = \int_{a}{x} f(\tilde x) d \tilde x$ for $f\in C[a,
    b]$. Then $T(cf + cg) = cTf + dTg$. It is easy to show that the operator is
    linear.
*** Example
    1. Let $X$ be the space of all polynomials defined on $[a, b]$. We can define a
       linear operator to be the derivative, $Tf = f'$. [fn:7]
    2. Given $A \in \R^{m\times n}$, $T \colon \R^n \rightarrow \R^m$, $X
       \rightarrow Ax$ is linear $T(ax + by) = aAx + bAy = aTx + bYy$.
    3. Let $k$ be a square-integrable function on $[a, b]^2$ and $X=L_2[a, b]$,
       then define $f\mapsto\int_{a}^{b} h(x, \cdot) f(x)\ dx$[fn:8] [fn:9]
** Theorem about linear operators
   Suppose that $T$ is linear, then
   1. $R(T)$ is a vector space
   2. $N(T)$ is a vector space.

   I think $R$ and $N$ are range and kernel, respectively. The proof is kinda
   easy.
* Lecture 6 <2018-11-06 Tue> 
** Regarding convergence of a function
   $\sup(f_n)\subset [0, 2/n]$, $f_n(0) = 0$, consider fixed $x\in [0, 1]$.
   Given any $\varepsilon > 0$, choose $N > 2/X$, then $X > 2/N > 2/N$ for
   $n>N$. Thus $x \in \sup(f_n)$ and $f_n(x) = 0$, $f_n$ converges point-wise to
   $0$.

   $f_n(x) = f(2n(n+1)(x - 1/2))$
** Injectivity of operators
   If $T$ is injective, there exists $T^{-1}\colon R(T) \rightarrow D(T)$ with
   $T^{-1}y =x$ for $Tx =y$, i.e., the inverse of $T$. It follows that $T^{-1}Tx
   = T^{-1}Ty = x$ and $TT^{-1}y = Tx = y$.

   Example: Given $A\in \R^{n\times n}$, $T\colon \R^n \rightarrow \R^m$, $x
   \mapsto Ax$.

   If $m < n$, $T$ can be injective if the rank of $A = n$, but it cannot be
   surjective. When $m > n$, then $T$ can be surjective, when the Rank of $A =
   m$, but it cannot be injective. If $m = n$, then $T$ is bijective if and only
   if the rank of $A = m = n$.
** Theorem
   Given vector spaces $X$ and $Y$, and a linear operator $T \colon D(T)
   \rightarrow Y$, then
   1. $T^{-1}\colon R(T) \rightarrow D(T)$ exists if and only if $T(x) = 0
      \implies x = 0$, i.e., the null space $N(T) = 0$. Then $T^{-1}$ is also a
      linear operator.
   2. If the dimension of the domain of $T$ is smaller than $\infty$, and
      $T^{-1}$ exists, then $\dim R(T) = \dim D(T)$.
*** Proof
    Assume that $T^{-1}$ exists then $T$ is injective and $Tx = 0 \implies x =
    0$. Conversely, assume $Tx_1 = Tx_2$, then $Tx_1 - Tx_2 = T(x_1 - x_2) = 0$.
    Thus, by assumption $x_1 - x_2 = 0 \implies x_1 = x_2$ and $T$ is injective.
    Hence the inverse $T^{-1}$ exists.

    To show that $T^{-1}$ is a linear operator: Given $y_i = T x_i$ and $x_i =
    T^{-1}y$, for $i = 1, 2$, then it follows that $T(\alpha x_1 + \beta x_2) =
    \alpha T x_1 + \beta T x_2 = \alpha y_1 + \beta y_2$ and $T^{-1}T(\alpha
    x_1 + \beta x_2) = T^{-1}(\alpha y_1 + \beta y_2)$. From this one can show
    that if $T^{-1}$ exists, it is also a linear operator.

    1. Let $\dim D(T) = n < \infty$, then $\dim R(T) \le n$, i.e., $\dim R(T)
       \le \dim D(T)$. This can be seen as follows: choose $n+1$ elements $y_1,
       \cdots, y_{n+1} \in R(T)$ and we choose them arbitrary, then we can find
       pre-images $x_1, \cdots, x_{n+1}\in D(T)$, it holds that $Tx_i = y_i$,
       for all $i$. Since we assumed $\dim D(T) = n$, the $x_i$ are linearly
       dependent, i.e., there exist $\alpha_i \in \R$ such that $\sum \alpha_i
       x_i = 0$ where not all $\alpha_i$ are zero. Now $T \sum_i^{n+1} \alpha_i
       x_i= \sum_{i=1}^{n+1} \alpha_i y = 0$, but not all $\alpha_i$ are zero.
       Thus we have found a set of linearly dependent vectors. Since we chose
       the vectors arbitrarily, we see that the dimension must be less than or
       equal to $n$.

       If we apply the same reasoning to the inverse operator, which we assume
       exists, we obtain in similar fashion that the $\dim D(T) \le \dim R(T)$.
       Thus, $\dim R(T) = \dim D(T)$.
** Lemma
   Let $X, Y, Z$ be vector spaces $T \colon X \rightarrow Y$, and $S \colon Y
   \rightarrow Z$ bijective operators, then we claim that $(ST)^{-1} = T^{-1}
   S^{-1}$.
** Definition: Bounded operators
   Given normed spaces $X$ and $Y$ and a linear operator, $T \colon D(T)
   \rightarrow Y$, $D(T) \subset X$, $T$ is defined to be bounded if there
   exists a constant $c$ such that $\Vert Tx \Vert \le c \Vert x \Vert$ and this
   has to hold for all $x \in D(T)$. A bounded linear operator maps bounded sets
   in $D(T)$ onto bounded sets in $Y$.

   We define the norm $\Vert T \Vert = \sup_{x \in D(T), \lambda \neq 0}
   \frac{\Vert T x \Vert}{\Vert x \Vert}$ to be the norm of $T$. It is
   straightforward to verify that this satisfies the properties for norm.

   For bounded linear operators, the bound can be computed by the supremum over
   $\Vert x \Vert = 1$. This is straightforward to see.
** Example
   Given $A \in \R^{n \times n}$, the linear operator $T \colon \R^{n}
   \rightarrow \R^{n}$ is bounded since $(\sup_{\Vert x \Vert= 1} \Vert A x
   \Vert)^2 = \sup x^{T} A^{T} A x = \lambda \max(A^T A)$, the largest
   eigenvalue of $A^{T}A$ (Rayleigh-Ritz theorem.)

   Note that for $A = U \sum V^T$, so that $A^{T} A = V \sigma^2 V^{T}$, thus
   $\lambda_{\max} = \delta_{1}^2$, where $\delta_1$ is the largest singular
   value of $A$.

   Let $X$ be the space of all polynomials on $[0, 1]$ and $\Vert f \Vert =
   \max_{x \in [0, 1]} \vert f (x) \vert$. The differentiation operator $T$ with
   $Tf = f'$ is not bounded. Since for $f_n(x) = x^n$, $\Vert f_n\Vert = 1$, all
   these functions are bounded above by $1$, hence the norm is $1$, whereas, the
   norm of the derivative is $n$ and this is unbounded.

   $T \colon C[0, 1] \rightarrow C[0, 1]$ by $(Tf)(x) = \int_{0}^{x} f(t)\ dt$.
   Then $\Vert T f\Vert = \max_{x \in [0, 1]} \vert \int_{0}^{1} f(t)\ dt\vert
   \le \max_{x \in [0, 1]} \int_{0}^{1} \vert f(t) \vert dt \le (1-0) \max_{x\in
   [0, 1]} \vert f(x) \vert = \Vert f \Vert$, thus $\Vert T \Vert \le 1$, but we
   can choose the function identical to $1$, then the norm is exactly equal to
   $1$.

   Define $c = \{x_n \in l_1 \vert \exists N \in \N \colon x_n = 0, \forall n >
   N\}$, with the $l_1$ norm. We define the operator $T\colon (x_1, x_2, x_3,
   \cdots) = (x_1, 2x_2, 3x_3, \cdots)$ is unbounded, we can compute $\Vert T
   e_i \Vert = i$, so if we have the sequence but the $\Vert e_i \Vert = 1$.
** Theorem
   Every linear operator on a finite dimensional normed space is bounded.
*** Proof
    Let $n$ be the dimension of $X$ and $\{e_1, \cdots, e_n\}$ a basis.

    Any $x\in X$ can be written as $X = \sum \alpha_i e_i$, thus $\Vert Tx \Vert
    = \Vert T \sum \alpha_i e_i\Vert \le \sum \Vert T \alpha_i e_i\Vert = \sum
    \vert \alpha_i \vert \le \max_{i} \Vert T e_i \Vert . \sum \vert \alpha_i
    \vert$. We define $\Vert x \Vert_0 = \sum \vert \alpha_i \vert$ defines a
    norm. Since all norms on finite-dimensional spaces are equivalent, there
    exist $c$ such that $\Vert x \Vert_0 \le c \Vert x \Vert$. Thus $\Vert T
    x\Vert \le \max \Vert T e_i \Vert \cdot c \cdot \Vert x \Vert$ and $T$ is
    bounded.
* Lecture 7 <2018-11-08 Thu> 
** Theorem about Bounded operators
   For linear operators, continuity and boundedness are equivalent.

   Continuity of $T$ means that $\forall \varepsilon > 0$, there exists a
   $\delta > 0$, such that $\Vert x - x_0 \Vert < \delta \implies \vert Tx -
   Tx_0 \vert < \varepsilon$.
*** Proof
    There is nothing to show for $T=0$, now we assume that $T$ is not the zero
    operator, i.e., $\exists r$ such that $\Vert T x \Vert \le r \Vert x \Vert$.
    Using linearity, we can write that $\Vert Tx - Tx_0\Vert = \Vert T (x -
    x_0)\Vert \le \delta \Vert x - x_0\Vert$. Choose $\delta =
    \varepsilon/\delta$, thus $\Vert x -x_0 \Vert < \delta \implies \Vert Tx -
    Tx_0 \Vert \delta \Vert x - x_0\Vert\le \gamma\cdot \delta =\varepsilon$ and
    $T$ is continuous.

    Conversely, assume that $T$ is continuous. Take arbitrary $y\in D(T)$,
    define $X = X_0 + \frac{\delta}{\Vert y \Vert} y$. Thus $\Vert x - x_0 \Vert
    = \Vert \frac{\delta}{\Vert y \Vert} \cdot y \Vert = \delta$. Since $T$ is
    continuous, $\Vert Tx - Tx_0 \Vert < \varepsilon$. Now $\Vert Tx - Tx_0\Vert
    = \Vert T \delta/\Vert y \Vert y \Vert = \frac{\delta}{\Vert y \Vert}\Vert T
    y \Vert < \varepsilon$ Multiplying by $\Vert y \Vert / \delta$, we get
    $\Vert T y \Vert < \varepsilon/\delta$\cdot \Vert y \Vert$ We call the last
    term $\gamma$.

    The second part of the proof shows that continuity in one point suffices to
    show boundedness. And boundedness means continuity at all points. Thus
    continuity at one point implies continuity at all points. Pretty interesting!
** Corollary
   Given a linear bounded operator $T$, it holds that 
   1. $x_n \rightarrow x$ implies that $Tx_n \rightarrow Tx$
   2. The null space of such an operator is closed
*** Proof
    These are basically properties of continuous functions.
** Definition
   We write that $T_1 = T_2$ if $D(T_1) = D(T_2)$ and $T_1x = T_2x$ for all $x
   \in D(T_1) = D(T_2)$. Furthermore $T\vert_B$ denotes the restriction to the
   set $B$, i.e., $T\vert_B \colon B \rightarrow Y$ with $T\vert_B x = Tx$ for
   all $x \in B$.

   The extension of $T$, denoted by $\tilde{T}\colon M \rightarrow Y$ where $D(T)
   \subset M$ is defined by $\tilde{T}x = Tx$, for all $x\in D(T)$.

   Example of extension. The set $X = Y = \R$, define $T$ by $Tx=x$, and $D(T) =
   [0, 1]. Then $\tilde{T}$ defined by $\tilde{T}x = \vert x \vert$ with
   $D(\tilde{T}) = [-1, 1]$ is an extension of $T$
** Theorem
   If $T \colon D(T) \rightarrow Y$ is a bounded linear operator, $D(T)$, part
   of a normed space, $Y$, a Banach space, then there is an extension
   $\tilde{T}\colon \bar{D(T)} \rightarrow Y$ with $\Vert \tilde{T} \Vert =
   \Vert T \Vert$. Furthermore, $\tilde{T}$ is a bounded linear operator.
*** Proof
    For any $x \in \bar{D}(T)$ consider the sequence $(x_n)_n$ in $D(T)$ that
    converges to $x$.

    $\Vert Tx_n - Tx_m \Vert = \Vert T(x_n - x_m)\Vert \le \Vert T \Vert \Vert
    x_n - x_m\Vert$. Since $x_m$ converges, $Tx_n$ is Cauchy and converges as we
    assumed $Y$ to be complete. The rest of the argument is trivial.
** Linear functionals
   A functional is a map from $X$ to $\R$ or $\C$. Given a functional $f$,
   $D(f)$ denotes the domain, $R(f)$ denotes the range of $f$. 

   For functionals, we typically write $f(x)$ and not $fx$, although $f$ is
   still an operator.
*** Example
    1. For a normed space $X$, $\Vert . \Vert \colon X \rightarrow \R$ is a functional.
    2. For $X=\R$, and $x_0 in X$, $f\colon X\rightarrow \R$, $x\mapsto x_0^{T}x
       = \langle x_0, x\rangle$.
    3. Linearity is defined as before, with the difference that $y$ is now $\R$
       if $X$ is a real or $\C$, if $X$ is a complex space.
*** Example
    1. The norm functional is not a linear functional. $\Vert \alpha x + \beta y
       \Vert \neq \alpha \Vert x \Vert + \beta \Vert y \Vert$. This is not true
       in general.
    2. Define $f(x) = x_0^{T}x$ is linear, clearly, because the scalar product
       is bilinear. It is linear in each variable.
    3. The evaluation functional given by the Dirac delta function $\delta_x f =
       f(x)$.
    4. The definite integral is a functional. Let $l$ denote the functional such
       that for $f$ in $C[a, b]$, $l(f) = \int_{a}^{b} f(x) dx$, then it is
       straightforward to verify that this is linear.
*** Remark
    Similarly, boundedness is again defined as: A linear functional is bounded
    if there exists a constant $c$ such that $\vert f(x) \vert \le c \cdot \Vert
    x \Vert$. and $\Vert v \Vert = \sup \vert f(x) \vert / \Vert x \Vert =
    \sup_{\Vert x \Vert = 1} \vert f(x) \vert$.
*** Theorem
    Let $f\colon D(f) \rightarrow K$ be a linear functional, then $f$ is
    continuous if and only if it is bounded.
*** Example
    1. For integrable functions on $[a, b]$, it is easy to see that the integral
       functional is bounded.
    2. The dot product example can be extended to $l_2$ by choosing a fixed
       element $a$ in $l_2$ and setting $f(x) = \sum a_i x_i$. Due to
       Cauchy-Schwarz inequality $\vert \langle x, y\rangle\vert \le \Vert x
       \Vert \cdot \Vert y \Vert$.
* Lecture 8 <2018-11-07 Wed> 
** Example
   $(x_n)_n$, it's basically a sequence of sequences. $x_n \in l_\infty$.

   $\delta_X f = f(x)$.

   The evaluation functional $\delta_X$ on $C[a, b]$ with norm $\Vert \cdot
   \Vert_\infty$ is bounded. But it might be unbounded with respect to another
   norm.
** Linear functionals
   The set of all linear functionals forms a vector space denoted by $X^{*}$.
   
   The algebraic dual space. For defining a vector vector space, we need the
   basic operations $+$ (addition) and $.$ scalar multiplication, which can be
   defined as follows: we take two functionals $f_1$ and $f_2$ and a scalar
   $\alpha$, is easy to write $(f_1 + f_2)(x) = f_1(x) + f_2(x)$ etc. This part
   is obvious.

   We can also consider the dual of the dual space $X^{**}$, the second
   algebraic dual space. It is clear that there is a canonical isomorphism
   between $X$ and $X^{**}$.

   There was an example with $V$ along with an orthogonal basis.
** Definition of isomorphism of vector spaces
** About finite linear operators
   Let us now consider finite dimensional vector spaces. Any linear operator
   between two fininte-dimensional vector space can be regarded as a matrix. To
   see this we have two finite dimensional spaces $X$ and $Y$ and a linear
   operator $T \colon X \rightarrow Y$. let $\{x_1, \cdots, x_n\}$ be a basis of
   $X$ and $\{z_1, \cdots, z_n\}$ be a basis of $Y$. 

   Then for each $x\in X$, we can write $X = \sum \alpha_i X_i$ and $y = Tx =
   \sum \alpha_i Tx_i$ and define $Tx_i = y_i$. Thus by knowing the images
   $y_i$, $T$ is uniquely defined. For any $z \in Y$, it can be written as $z =
   \sum \beta_j z_j$ as well as $y_j = Tx_i = \sum \gamma_{ji}z_j$.

   Now we have two representations in $z_j$, $j = 1, \cdots, m$. It follows that
   $\beta_j = \sum_{i=1}{n} \gamma_{ji} \alpha_i$ and that $y = Tx$ is
   determined by knowing the coefficients $\gamma_{ji}$, which can be written in
   matrix form as

   $$T_\mu = [\gamma_{ji}]_{j=1, \cdots m; i =1, \cdots m}$$
   
   Then $\beta = T_\mu \alpha$.
** Example
   Consider the discrete dynamical system $\phi \colon \R^2 \rightarrow \R^2$ by
   $\phi(x) = [\lambda x_n, \mu x_2 + (\lambda^2 - \mu)x^2n]^T$

   The Korpman operator $K$ is an infinite-dimensional operator defined by $Kf =
   f\circ \phi$, i.e., $(Kf)(\lambda) = f(\phi(x))$ for $f \in L_{\infty}$. This
   operator apparently plays an important role in Dynamical system.
* Lecture 10 <2018-11-15 Thu>
** Koopman operator
   $Kf = f\circ I$

   Consider the discrete dynamical system $\phi \colon \R^2 \rightarrow \R^2$ by
   $\phi(x) = [\lambda x_n, \mu x_2 + (\lambda^2 - \mu)x^2n]^T$

   Then the space is spanned by functions $\{x_1, x_2, x_1^2\} forms a so-called
   Koopman-invariant subspace. Let $f_1(\bf{x}) = x_1$, $f_2(\bf{x}) = x_2$,
   $f_e(\bf{x}) = x_n^2$, then any function from this subspace can be written as
   $f = \sum_{i=1}^{3} \alpha_i f_i$ and $g=Kf = K\sum(\alpha_i f_i) = \sum
   \alpha_i Kf_i$. We call the term $Kf_i = g_i$.

   $g_1(x) = Kf_1(x) = f_1(\phi(x)) = \lambda x_1 =\lambda f_1(x)$.

   $g_2(x) = Kf_2(x) = f_2(\phi(x)) =\mu x_2 + (\lambda^2 - \mu)x_1^2 - \mu
   f_2(x) + (\lambda^2 - \mu)f_3(\lambda)$
   
   $g_3(x) = Kf_3(x) = f_3(\phi(x)) = \lambda^2 x_1^2 = \lambda^2 f_3(x)$

   Thus $g = Kf = \alpha_1 \lambda f_1 + \alpha_2[\mu f_2 + (\lambda^2 -
   \mu)f_3] + \alpha_3 \lambda^2 f_3 = \alpha_1\lambda f_1 + \alpha_2 \mu f_2 +
   (\alpha_2(\lambda^2 - \mu) + \alpha_3 \lambda^2)f_3$

   Now we can write this as a matrix.

   It follows that

   $\gamma_{11} = \lambda$, $\gamma_{12} = 0$, $\gamma_{13} = 0$

   $\gamma_{21} = 0, \gamma_{22} = \mu, \gamma_{13} = 0$

   $\gamma_{31} = 0, \gamma_{32} = \lambda^2 - \mu, \gamma_{23} = \lambda^2$

   The following is a matrix representation: 

   | $\mu$ | 0             | 0           |
   | 0     | $\mu$         | $0$         |
   | $0$   | $\mu^2 - \mu$ | $\lambda^2$ |
   
   That is defining, $\bar{f} = [f1, f2, f3]^T$ and $\alpha = [\alpha_1,
   \alpha_2, \alpha_3]^T$.

   We obtain $f = \alpha^T f$ and $g=(T_\mu \alpha)^T\bar{f}$.

   Note that $\varphi_1(x) = x_1$, $\varphi_2(x)=x_2 - x_n^2$, $\varphi_3(x) = x_1-x_n^2$ are
   eigenfunctions. Corresponding to the eigenvalues

   $\lambda_1 = \lambda \cdot; Ke_1 = \lambda \varphi_1$

   $\lambda_2 = \lambda^2; K\varphi_2 = \lambda^2e_2$

   $\lambda_3 = \mu; Ke_3 = [\mu X_2 + (\lambda^2 - \mu)x_1^2 - \lambda^2 x_n^2]
   = \mu x_2 - \mu x_n^2 = \mu(x_2 - x_n^2) = \mu \varphi_3$
** Matrix representation
   Assume now again that $X$ is a vector space with $\dim X = n$ and that
   $\{x_1, \cdots, x_n\}$ forms a basis. Given a linear functional $f$, we
   obtain for $X = \sum_{i=1}^{n} \alpha_i X_i$ that $f(x) = f(\sum \alpha_i
   x_i) = \sum \alpha_i f(x_i) = \sum\alpha_ic_i$. We call the last term our
   coefficient $c_i = f(x_i)$. Thus $f$ is uniquely determined by the values
   $c_i, i=1, \cdots, n$.

   Conversely, any set of values values $\alpha_i, i =1, \cdots, n$ uniquely
   defines a linear functional. A special set of functionals is defined as
   follows: $f_j(x_i) = \delta_{ij}$. It's one when $i=j$, and $0$ otherwise. We
   call this the dual basis of $\{x_1, \cdots, x_n\}$.
** Theorem
   Let $X$ be again an $n$-dimensional vector space with basis $\{x_1, \cdots,
   x_n\}$. Then $\{f_1, \cdots, f_n\}$ as defined above is a basis of $X^{*}$.
   As a result, we have $\dim X^{*} = \dim X$.
*** Proof
    It's kinda easy. We just show that the maps $f_j$ is a basis and we're done.
** Theorem
   A fininte-dimensional vector space is algebraically reflexive, i.e., the
   canonical embedding is an isomorphism between $X$ and $X^{**}$.
** Normed space of operators
   Let $X$ and $Y$ be arbitrary normed spaces, then the set $B(X, Y)$ of all
   bounded linear operators from $X$ to $Y$ is again a normed space.

   We need addition, scalar multiplication and a norm, and define:
   1. $(T_1 + T_2)x = T_1 x + T_2x$ for any $T_1, T_2 \in B(X, Y)$
   2. $(\alpha T) x = \alpha Tx$ for any $T\in B(X, Y), \alpha \in K$
   3. $\Vert T\Vert$ is the supremum norm that we have already defined.
** Theorem
   $B(X, Y)$ is a Banach space if $Y$ is a Banach space, i.e., $B(X, Y)$ is
   complete if $Y$ is complete.[fn:10]
** Definition
   The set of all bounded linear functionals on $X$ is a normed space with
   $\Vert f \Vert = \sup \vert f x\vert / \Vert x \Vert$ for $x \neq 0$.

   From the above theorem, since $\R$ is complete, the space of all bounded
   linear functionals converge. This is called this *dual space* (the
   continuous/topological dual) and is denoted by  $X'$.

   Remark: The algebraic dual space $X^{*}$ contains all linear functionals of
   $X$, whereas $X'$ contains only the bounded linear operators. 
** About $X'$ and $X^{*}$
   The space of all bounded linear functionals on $X$, given by $X'$, forms a
   linear subspace of $X^{*}$.

   Assume that $f$ and $g$ are bounded by $a$ and $b$, $\vert f(x) \vert \le a
   \Vert x \Vert$, $\vert g(x) \vert \le b \Vert x \Vert \forall x\in X$.

   Using triangle inequality, we can see that $af + bg$ is bounded if $f$ and
   $g$ are bounded. For scalars multiplication, it is similarly true. Thus it
   forms a linear subspace.
** Examples
   1. $(\R^n)' = \R^n$
   2. $(l^1)' = l^{\infty}$
   3. For $1 < p < \infty$ and $\frac{1}{p} + \frac{1}{q} = 1$, $(l^p)' = l^q$.
      Here $=$ means there exists an isomorphism.
** About $l^p$ and $l^q$
   Given $1 \le p \le \infty$, with $\frac{1}{p} + \frac{1}{q} = 1$. Take any
   $(y_n)_n \in l^p$, then $f\colon l^p \rightarrow \R$, $(x_n)_n \mapsto \sum
   x_n y_n$ is a bounded linear functional. The norm of this functional is
   $\Vert f \Vert = \Vert y \Vert_q$.
* Lecture 11 <2018-11-20 Tue>
** About $l^p$ and $l^q$
   $\frac{1}{q} + \frac1p = 1$, $(y_n)_n \in L^q$, $f\colon l^p \rightarrow \R$,
   $(x_n)_n \mapsto \sum x_n y_n$

   Note that $\sum \vert x_n y_n\vert \le \Vert x \Vert_p \cdot \Vert x \Vert_q$
   done to the Holder inequality.
** Theorem
   For $1\le p < \infty$, $(l^p)' \equiv l^q$ and an isometric isomorphism is
   given by $T \colon l^q \rightarrow (l^p)'$, $(Ty)(x) = \sum_{n=1}^{\infty}
   x_n y_n$.
*** Proof
    $\Vert Tt \Vert_{l^p}' = \Vert y \Vert_q$ as shown above and $T$ is linear.
    The $N(T)$ is only the sequence $0$, meaning that the mapping is injective.
    Show that the mapping is also surjective. So for any given functional, we
    need to find a corresponding $y$.

    Take any $x' \in (l^p)^{*}$ and define $y = (y_n)_n$ with $y_n = x'(e_n)$
    then $y \in l^q$: Fix $N \in \N$ for $p > 1$, (can be shown for $p=1$)
    construct the sequence: $\sum_{n=1}^{N} \vert y_n \vert^q = \vert_{n=1}^{N}
    \vert y_n \vert^q = \sum \frac{\vert y_n \vert^q}{y_n} y_n = \sum
    \frac{\vert y_n\vert^q}{y_n} x'(e_n) = x'(\sum \frac{\vert y_n \vert^q}{y_n}
    e_n$ (this is using the linearity). Now we can use that $x'$ is bounded.

    $X'(\sum \frac{\vert y_n \vert^q}{y_n} e_n \le \Vert X' \Vert \sum \vert
    y_n\vert^q}{y_n} e_n \Vert = \Vert X'\Vert \left(\sum (\vert
    y_n\vert^{q-1})^p\right)^{1/p} = \Vert X'\Vert \left( \vert y_n
    \vert^q\right)^{1/p}$

    Here $\frac1p + \frac1q = 1$ implies that $\frac1p = \frac{q-1}{q} \implies
    (q-1)p = q$.

    Divide by $\sum_{i=1}^{N} \vert y_n \vert^q)^{1/p}$, then
    $\left(\sum_{n=1}^{N} \vert y_n \vert^q\right)^{1-1/p} \le \Vert X'\Vert$.
    For $N \rightarrow \infty$, we obtain $\Vert y \Vert_q \le \Vert X'\Vert <
    \infty$

    We have shown $y\in l^q$, i.e., for each functional $x'$, we can find such a
    $y$. Now, $(T_y)(e_n) = (y_n)$ and also we define $y_n = X'(e_n)$. This
    means that it is really an isomorphism.

    Thus $Ty = x'$ on span $\{e_1, \cdots,\}$ which is a basis of $l^p$.
** About reflexiveness
    The dual of $l^\infty$ is not $l^1$, but a different one.
** Inner Product spaces and Hilbert spaces 
*** Definition
    In vector spaces we have addition and scalar multiplication. In normed
    vector spaces, we additionally have a norm $\Vert . \Vert$ which gives us
    lengths of vectors. A norm induces a metric by $d(x, y) = \Vert x - y
    \Vert$.

    However, we have not yet defined the notion of orthogonality in $\R^n$. Two
    vectors are orthogonal if $\langle x, y \rangle = x^{T} y = x \cdot y = 0$.

    The inner product induces a norm and thus also a metric by $\Vert x \vert =
    \langle x, x \rangle^{1/2}$. Here $\langle x, x \rangle = x^{T} x =
    \sum_{i=1}^{n} \hat{x}_i = \Vert x \Vert_2^2$ induces the standard Euclidean
    norm.

    With the inner product, we can thus compute angles in $\R^n$. This concept
    will be generalized in what follows. The resulting space with the inner
    product is called an inner product space. Inner product spaces that are
    complete are called *Hilbert spaces*

    | normed space        | complete normed space = Banach Space         |
    | inner product space | complete inner product space = Hilbert space |
*** Definition
    Let $X$ be a vector space. A mapping $\langle ., \cdot \rangle \colon X
    \times X \rightarrow K$ ($=\R$ or $=\C$ as usual) is called an inner product
    space (or scalar product.) if 
    1. $\langle x_1 + x_2 , y \rangle = \langle x_n , y \rangle + \langle x_2, y\rangle$, $x_1, x_2, y \in X$
    2. $\langle \lambda x, y \rangle = \lambda \langle x, y \rangle$, $x, y, \in X, \lambda \in K$.
    3. $\langle x, y\rangle = \overline{\langle y, x \rangle}$
    4. $\langle x, x \rangle \ge 0$, for all $x\in X$.
    5. $\langle x, x \rangle = 0 \iff x = 0$.
*** Remark
    It follows $\langle x, y_1 + y_2 \rangle = \overline{\langle y_1 + y_2, x
    \rangle} = \overline{\langle y_1, x\rangle} + \overline{\langle y_2,
    x\rangle}$ and

    $\langle x, \lambda y\rangle = \lambda \langle x, y\rangle$ similarly.
*** Theorem
    Let $X$ be a vector space and $\langle . , . \rangle$ an inner product, then
    $\vert \langle x, y \rangle\vert^2 = \langle x, x \rangle \cdot \langle y, y
    \rangle$ for all $x, y \in X$. Equality when $x$ and $y$ are linearly
    dependent.
**** Proof
     For arbitrary $\lambda \in K$, we can write $0 \le \langle x + \lambda y,
     x + \lambda y \rangle = \langle x, x \rangle + \langle \lambda y, x
     \rangle + \langle x, \lambda y \rangle + \langle \lambda x, \lambda y
     \rangle$.

     Now it's kinda easy to see when we put $\lambda = -\frac{\langle x, y
     \rangle}{\langle y, y \rangle}$ for $y \neq 0$.
*** Lemma
    Assigning $x \mapsto \langle x, x \rangle^{1/2}$ indeed defines a norm.
**** Proof
     The proof is not too hard hence skipped.
* Lecture 12 <2018-11-22 Thu>
** Definition
   A normed space $(X, \Vert . \Vert)$ is called an inner product space (or
   pre-Hilbert space) if an inner product $\langle ., .\rangle$ exits such that
   $\langle x, x \rangle^{1/2} = \Vert X \Vert$ for all $x\in X$.

   An easy example is $\R^n$ with the standard inner product.

   We have seen that an inner product induces a norm. What about the other case?
   Given a norm, can we get an inner product? We can do this in the following way:

   $\langle x, y \rangle = \frac{1}{4}(\Vert x + y \Vert^2 - \Vert x - y
   \Vert^2)$ (for real numbers.)

   $\langle x, y\rangle = \frac{1}{4}\left(\Vert x + y\Vert^2 - \Vert x - y
   \Vert^2 + i \Vert x +iy\Vert^2 - i\Vert x - iy\Vert^2\right)$. For complex
   numbers.[fn:11]

   Furthermore, the so-called parallelogram law holds:

   $\Vert x + y \Vert^2 + \Vert x - y \Vert^2 = 2(\Vert x \Vert^2 + \Vert y
   \Vert^2)$, this can be noticed easily. It's called Parallelogram law because
   it has something to do with parallelograms.
** Lemma
   The inner product is a continuous mapping from $X \times X$ to $K$.
*** Proof
    Let $x_n \rightarrow x$ and $y_n \rightarrow y$, we need to show that
    $\langle x_n, y_n \rangle$ converges to $\langle x, y \rangle$. This is
    straightforward to verify. It involves triangle inequality and
    Cauchy-Schwarz.
** Theorem (When is a normed space, an inner product space?)
   A normed space $(\lambda, \Vert . \Vert)$ is an inner product space if and
   only if the parallelogram law holds for all vectors.
*** Proof
    We have already seen that an inner product satisfies the parallelogram law.
    Now, one have to prove this the other way around.

    We consider only $\R$. We need to show that $\langle x_1 + x_2, y \rangle =
    \langle x_1, y \rangle + \langle x_2, y \rangle$.

    Define $\langle x, y \rangle = \frac{1}{4}(\Vert x + y \Vert^2 - \Vert x-
    y\Vert^2)$ as shown, then, $\langle x_1 + x_2, y \rangle =
    \frac{1}{4}\left(\Vert x_1 + x_2 + y \Vert^2 - \Vert x_1 +x_2 - y \Vert^2$.

    Some lengthy calculations and we end up with the result.
** Examples
   1. $\C^n$ with the inner product $\langle x, y \rangle = \sum x_i \bar{y_i}$
      is a Hilbert space.
   2. $l_2$ is a Hilbert space with $\langle x, y \rangle = \sum x_i \bar{y}_i$
   3. $l_2(\Omega)$ where $\Omega \in \R^n$ is an open subset is a Hilbert space
      with $\langle f, g \rangle = \int f(x)\overline{g(x)} dx$
   4. $C([a, b]) with $\langle f, g \rangle = \int_{a}^{b} f(x)g(x)\, dx$ (only
      real-valued functions.) This is apparently not a Hilbert space. This is an
      inner product space. This example is similar to an exercise in one of the
      tutorials.
   5. Let $\R^{m\times n}$ denote the set of all real $m\times n$ matrices.
      Define $\langle A, B\rangle = \tr(A^TB)$. For $A = (a_{ij}), B= (b_{ij})$,
      we obtain $[A^TB]_{ij} = \sum [A^T]_{ik} [B]_{kj} = \sum a_{ki}b{kj}$ and
      $\tr(A^TB) = \sum_{i}(A^TB)_{ii} = \sum_i\sum_j a_{ki}b_{ki}$. Then
      induced norm, is $\Vert A \Vert = \sum A, A\rangle^{1/2} = \left(\sum_i
      \sum_k a_{ki}^2\right)^{1/2} = \Vert A \Vert_F$, i.e., the Frobenius norm.

      Apparently, we can use the parallelogram law to show that $l^p$ when
      $p\neq 2$ is not a Hilbert space.
* Lecture 13 <2018-11-27 Tue>
** Example (parallelogram law is invalid)
   The space $l^p$ for $p \neq 2$ is not a Hilbert space since it does not
   satisfy the parallelogram law.

   Define $x = (1, 1, 0, \cdots)$ and $y = (1, -1,0, \cdots)$. Both of them are
   in $l^p$.

   The norm of $x$ is $2^{1/p}$ and it is same as the norm of $y$.

   The norm of $x +y$ is $2$.

   The norm is $x - y$ is $2$.

   The parallelogram law says $4 + 4 = 4(4^{1/p})$ which is not true for $p \neq
   2$.
** Orthogonality
   With the aid of the inner product, we can now introduce the notion of
   orthogonality as already mentioned above.
   
   Let $X$ be an inner product space, then $x, y \in X$ are called *orthogonal*
   denoted by $x \perp y$ if $\langle x, y \rangle = 0$.

   Two subsets $A$ and $B$ are orthogonal if $\langle x, y \rangle = 0$ for
   every $x\in A$ and $y\in B$.

   Now, given a set $A$, we want to know the set of all elements that are
   orthogonal to $A$. $A^{\perp} =\{y \in X\vert x \perp y, \forall x \in A\}$
   is called orthogonal complement of $A$.

   $A^{\perp}$ is a closed subset of $X$. (Kinda easy to see in terms of
   continuity of the inner product and $y$ being the inverse of a closed set)
   The proof in the class used the fact that if a sequence in $A^\perp$
   converges, then the limit will be orthogonal to $x$ as well.
** Definition
   Given the elements $x, y$ of a vector space $X$, the segment joining $X$ and
   $Y$ is defined as $\{z \vert z = \alpha x + (1-\alpha)y, 0 \le \alpha \le
   1\}$

   A subset $A \subset X$ is said to be *convex* if for every combination $x, y
   \in A$ is in the set $A$.
** Theorem
   Let $H$ be a Hilbert space and $K \subset H$ closed and convex. Furthermore,
   let $x_0 \in H$, then there exists a unique $x$ in the set $A$ which has the
   shortest distance with $\Vert x - x_0 \Vert = \inf_{y \in K} \Vert y =
   x_0\Vert$[fn:12]
*** Proof
    If $x_0 \in K$ simply choose $x = x_0$. The proof is easy.
** Lemma
   Let $K$ be a closed and convex subset of $H$. For $x \in K$, the following
   statements are equivalent:

   1. $\Vert x_0 - x\Vert = \inf_{y\in Y} \Vert x_0 - y\Vert$
   2. $Re \langle x_0 - x, y -x \rangle \le 0$ for all $y \in K$.
*** Proof
    Geometric interpretation: assume that $K=\R$, then $\langle a, b\rangle =
    \Vert a \Vert \Vert b\Vert \cos(a, b)$ and $\langle a, b \rangle <0$ implies
    the angle is obtuse.

    Thus $Re\langle x_0 - x, y - x\rnagle \le 0$ means that the angle between
    $x_0 - x$ and $y-x$ is obtuse ($K = \R$)
** Definition
   A vector space $X$ is defined to be the direct sum of the subspaces $Y$ and
   $Z$, denoted by $Y = Y \oplus Z$ if each $x \in X$ have a unique
   decomposition such that $x = y + z$, where $y\in Y$ and $z \in Z$.

   The mapping defined above is in general a non-linear projection. (a diagram
   was drawn about circles)

   Reminder: a projection onto a vector space is a mapping $P$ with $P^2 = P$
** Theorem
   Let $U \neq \{0\}$ be a closed subspace (now just a subspace, not convex) of
   a Hilbert space $H$. Then there exists a linear projection $P_u$ from $H$
   onto $U$ with $\Vert P_u \Vert = 1$ and $N(P_u) = U^{\perp}$. Furthermore,
   $Id - P_u$ is a projection onto $U^{\perp}$ with $\Vert Id - P_u\Vert = 1$.
   It holds that we can split this Hilbert space into $H = U \oplus U^{\perp}$.
   And this i a linear projection [fn:13]
* Lecture 15 <2018-12-06 Thu> 
** Review (Bessel's inequality)
   $\sum \vert \langle x, e_i \rangle \vert^2 \le \Vert x\Vert^2$
   
   Some inequality that happened last Thursday.
** Fourier coefficients
   The inner product $\langle x_i, e_i\rangle$ are called Fourier coefficients.

   If $\{e_i \vert i \in \N\}$ is a orthonormal basis, we obtain equality $\Vert
   x \Vert^2 = \sum \vert \langle x_i, e_i \rangle \vert^2$.
** Lemma
   Let $\{e_i, i \in \N\}$ be an orthonormal system and $x,y \in H$. Then you
   can show that $\sum_{i=1}^{\infty} \vert\langle x_i, e_i \rangle \langle e_i
   y\rangle \vert < \infty$.
*** Proof
    The proof simply uses the Holder's inequality.

    $\sum \vert \langle x, e_i \rangle \langle e_i, y\rangle \vert \le (\sum
    \vert \langle x, e_i \rangle \vert^2)^{1/2} (\sum \vert \langle e_i, y
    \rangle \vert^2)^{1/2} \le \Vert x \Vert \Vert y \Vert < \infty$
** Difference between orthonormal basis and orthonormal system
   Consider $\R^3$, then $e_1$ and $e_2$ form an orthonormal system. But it is
   not a basis, clearly.

   One can calculate the bessel's inequality thing.

   There was something about Paiseval's equality which was mentioned in the
   lecture.
** Theorem
   For an infinite-dimensional Hilbert space $H$. The following statements are equivalent

   1. $H$ is separable.
   2. All orthonormal basis are countable.
   3. There is at least one orthonormal basis
*** Proof (idea)
    1 to 2. Start with an orthonormal basis, we must show that it must be
    countable. Take two vectors $e_i$ and $e_j \in S$, then $\Vert e_i - e_j
    \Vert^2 = \sum \langle e_i - e_j, e_i - e_j\rangle= \Vert e_i\Vert^2 + \Vert
    e_j \Vert^2 = 2$. This means that the distance between two basis vectors are
    always two.

    Take the neighbourhood $B(e_i, \frac\sqrt{2}{3}) \cap B(e_j \sqrt{2}, 3) =
    \emptyset$. It is empty in $S$.

    This is apparently similar to the fact that $l^\infty$ is not separable?

    So if $S$ were uncountable, then we could have an uncountable number of
    disjoint sets. This contradicts the fact that $H$ is separable. Why? $H$ has
    a countable basis, but then if we have a set of disjoint open sets, then we
    can define an injection between our uncountable set and the countable set.

    2 to 3 is clear.

    3 to 1. The idea is that we take linear coefficients that are rational. Then
    we show that this set is dense in $H$ and then you're done.
** How does non-separable Hilbert spaces?
   Consider the space of functions $f\colon \R \rightarrow \R$ with the property
   that $f(x)\neq 0$ only for a countable set and the property that $\Vert f
   \Vert < \infty$, where $\Vert \cdot \Vert$ is the norm induced by the inner
   product. $\langle f, g \rangle = \sum_{x\in \R} f(x)g(x)$

   How do we show that this is not separable? 

   Define $f_y(X) = 1$ when $x \neq y$ and $0$ otherwise. For $y_0 \neq y_1,
   \Vert f_{y_0} - f_{y_1} \Vert = \Vert f_{y_0}\Vert^2 - 2\langle f_{y_0},
   f_{y_1}\rangle + \Vert f_{y_1}\Vert^2 = 2$

   We obtain an uncountable number of disjoint sets. Thus the space cannot be
   separable.
** Fourier series
   We consider the space $L^2[0, 2\pi]$, we define the set of basis functions:
   $S = \{\frac{1}{\sqrt{2\pi}} I} \cup \{\frac{1}{\sqrt{\pi} \cos(nx)}\} \cup
   \{\frac{1}{\sqrt{\pi}}\sin(nx)\}$ See example 3.18 (iii).

   The inner product is defined by $\langle f, g \rangle = \int_0^{2\pi}
   f(x)g(x)\ dx$. We can use the following identities to show that $S$ is indeed
   an orthonormal system.

   $\int_0^{2\pi} \cos(mx) \cos(nx)\dx$ is $0$ when $m\neq n$ and $2\pi$, when
   $m$ and $n$ are $0$, and it is $\pi$ if $m = n$, but not both $0$.

   Similarly, for the $\sin$, $\int_{0}^{2\pi} \sin{mx}\sin{nx}\ dx$ is $0$,
   when $m\neq n$ or $m=n=0$ or $\pi$, when $m=n\neq 0$.

   Also $\int_0^{2\pi} \sin mx \cos nx\ dx = 0$. Thus $\langle
   \frac{1}{\sqrt{\pi}} \cos mx, \frac{1}{\sqrt{\pi}} \cos nx\rangle =
   \delta_{m, n}$ for $m \neq 0, n \neq 0$.

   Holds the same for all other combinations. Hence $S$ is an orthonormal
   system.
** Example
   A trigonometric series is defined by $a_0 + \sum_{n=1}^\infty][a_k \cos(kx) +
   b_k \sin(kx)]$. Let $f$ be $2\pi$ periodic and continuous. Then the
   coefficients are defined by

   $a_0 = \frac{1}{2 \pi} \int_{0}^{2\pi} f(x)\ dx, a_k = \frac{1}{\pi}
   \int_0^{2\pi} f(x) \cos(kx)\ dx, b_k = \frac{1}{\pi} \int_0^{2\pi}
   f(x)\sin(kx)\ dx$.

   We and write the Fourier series as $\tilde{a_0} \frac{1}{\sqrt{2\pi}} I
   +\sum_{n=1}^{\infty} \tilde{a}_n \frac{1}{\sqrt{\pi} \cos(kx) + \tilde{b}_n
   \frac{1}{\sqrt{\pi} \sin(kx)}$.

   We know that $\tilde{a}_0 = a_0 \sqrt{2\pi} = \langle f, \frac{1}{\sqrt{2\pi}}I\rangle$.

   Similarly, we can express everything as a an inner product.

   That is, we write $f$ as $\sum_{e\in S} \langle f, e \rangle e$
** Example
   Let us consider the so called square wave function defined by, $f(x) = 1$
   between $0$ and $\pi$ and it is $-1$ between $\pi$ and $2\pi$.

   We can get that $a_k = 0$. $b_k = 1$ if $k$ is odd and $-1$ if $k$ is even.

   Another function is the sawtooth function.
* Lecture 16 <2018-12-11 Tue>
** Theorem
   Suppose $e_n$ is an orthonormal sequence in a Hilbert space $H$ (if an
   orthonormal set is countable, then we can arrange it as a sequence)

   1. The series $\sum_{i=1}^{\infty} a_ne_n$ converges if and only if
      $\sum_{n=1}^{\infty} \vert a_n \vert^2$ converges.
   2. If $\sum_{n=1}^{\infty} a_ne_n$ converges, then the coefficients $a_n$ are
      the Fourier coefficients $\langle x, e_n\rangle$ where $x$ is the element
      in $H$ we are approximating. Thus we can write $x = \sum_{n=1}^{\infty}
      \langle x, e_n \rangle e_n$.
*** Proof
    $H$ and $\R$ are both complete. Thus, a Cauchy sequence in $H$ converge if
    and only if the corresponding sequence in $\R$ is cauchy. To show this,
    define, $s_n = \sum_{k=1}^{n} a_ke_k$ and $\delta_n = \sum_{k=1}^{n} \vert
    a_n \vert^2$.

    Due to orthonormality, $\Vert s_n - s_m \Vert^2= \Vert \sum_{n=m+1}^{n} a_k
    e_k \Vert^2 = \sum_{k=m+1}^{n} \vert a_k\vert^2 = \delta_n - \delta_m$. Here
    we assume without loss of generality that $n > m$. Thus, the second
    statement can be seen as follows: $\langle s_n, e_j \rangle = \langle
    \sum_{k=1}^{n} a_n e_n , e_j \rangle = \sum_{k=1}^{n} a_n \rangle e_n, e_j
    \rangle = a_j$ for ($j \le n$)

    Since by assumption, $s_n \rightarrow x$ for $n\rightarrow \infty$.

    $a_j = \langle s_n, e_j \rangle \rightarrow \langle x, e_j \rightarrow$, (we
    have shown that the inner product is continuous.)

    Thus $a_j = \langle x, e_j \rangle$
** Orthonormal Polynomials
   [fn:14] Instead of using trigonometric basis functions for the Fourier
   analysis, we can use sets of orthonormal polynomials. Example, Legendre,
   Hermite or Laguerre Polynomials.
** Legendre Polynomials
   The Legendre Polynomials can be defined in terms of the generating functions
   $H(x, \gamma) = \frac{1}{(1-2x\gamma + \gamma^2)^{1/2}}$ This can be
   developed in a power series in $r$ so that $H(x, \gamma) = P_0(x) +
   P_1(x)\gamma + P_2(x) \gamma^2 + \cdots$

   Set $y = 2x\gamma - \gamma^2$, use $(1-y)^{-1/2} = \sum \binom{2k}{k}
   \frac{y^k}{2^{2k}}$.

   This will eventually result in $P_0(x) = 1, P_1(x) = x, P_2(x) =
   \frac{1}{2}(3x^2 - 1), P_3(x) = \frac{1}{2}(5x^3 - 3x)$.

   These polynomials are called Legendre polynomials and it holds that $P_n(-x)
   = (-1)^nP_n(x)$. Furthermore, $P_n(1) =1$ and using the previous property,
   $P_n(-1) = (-1)^n$.

   The polynomials can be defined recursively by $P_0(x) = 1, P_0(x) = x$, and
   $(n+1)P_{n+1}(x) - (2n+1)xP_n(x) + nP_{n-1}(x) = 0$.

   For instance, $2P_2(x) = 3x\cdot x + 1 = 0 \implies P_2(x) =
   \frac{1}{2}(3x^2 - 1)$.

   If we can now define the inner product $\langle f, g\rangle = \int_{-1}^{1}
   f(x) g(x)\ dx$, then $\langle P_n(x), P_m(x) \rangle = 0$ for $m\neq n$. That
   is, we defined a set of orthogonal, but not yet orthonormal functions. The
   normalized Legendre polynomials, denoted by lower case $p_n$ are $p_n(x) =
   (\frac{2n+1}{2})^{1/2} P_n(x)$.

   Any function on $(-1, 1)$ can now be expanded in a series of Legendre
   polynomials, similar to the standard Fourier expansion.
** Hermite polynomials
   Hermite polynomials are orthogonal on $(-\infty, \infty)$ with the weight
   function $\exp{-x^2/2}$. Define $\phi(x) = \exp{-x^2/2}$, then $\phi'(x) =
   -x\phi(x)$, $\phi''(x) = (x^2 - 1)\phi(x)$. We define $H_n(x) = (-1)^n
   \exp(x^2/2) \frac{d^n}{d x^n2} \phi(x)$ to be the Hermite polynomial.

   This can be defined recursively by $H_{n+1}(x) = xH_n(x) - H_n(x')$. We then
   obtain, $\int_{-\infty}^{\infty} \exp{-x^2/2} H_m(x) H_n(x) = \delta_{m,n} n!
   \sqrt{2\pi}$.

   That is, the polynomials are orthogonal with respect to the inner product
   $\langle f, g \rangle = \int_{-\infty}^{\infty} f(x) g(x) \exp{-x^2/2}\ dx$,
   but not orthogonal.

   The normalized Hermite Polynomials are given by $H_n(x)/((n!) \sqrt{2\pi})$.
   We can expand, and arbitrary function $f(x)$ in an series of Hermite
   polynomials. $f(x) = \sum_{n=0}^{\infty} a_n H_n(x)$, where $a_n =
   \frac{1}{n! \sqrt{2\pi}} \langle f, H_k\rangle$
** Laguerre Polynomials
   The last set of orthonormal polynomials we want to consider are the so-called
   Laguerre polynomials which are orthogonal on $(0, \infty)$ with weight
   function $\rho(x) = x^ae^{-x}$, with $a> -1$. $a$ is typically zero.

   We define $\phi_n(x)=x^{a+n} \exp{-x}$ and $L_n^a(x) = (-1)^n x^{-a} \exp{x}
   \frac{d^n}{dx^n} \phi_n(x)$

   The laguerre Polynomials are orthogonal with respect to $\langle f, g\rangle
   = \int^{0}^{\infty} f(x) g(x) x^a \exp^{-x}\ dx$.

   The Laguerre polynomials can be defined recursively and be used for series
   expansions.
* Lecture 17 <2018-12-13 Thu>
** Adjoint operators
   We now want to introduce the adjoint operator of a bounded linear operator
   but first we need a few auxiliary results. (Something like Reiz's
   representation theorem for bilinear forms.)

   The representation theorem states that, given a bounded linear functional $f$
   on $H$, it can be written as $f(x) = \langle x, z\rangle$ for $z \in H$ (this
   element was uniquely, defined.)

   Let $h$ denote a sesquilinear functional (linear in the first,
   conjugate-linear in the second argument.) Here conjugate-linear means $h(x,
   ay_1 + by_2) = \overline{a}h(x, y_1) + \overline{b}h(x, y_2)$.

   For normed spaces, $X$ and $Y$, $h$ is said to be bounded if $\exists c$ such
   that $\vert h(x, y) \vert \le c \Vert x \Vert \Vert y \Vert$, for all $x, y$.
   If this property holds we call it a bounded sesquilinear form (form and
   functional are used interchangeably)

   Furthermore, $\Vert h \Vert = \sup \frac{\vert{h(x, h)}}{\Vert x \Vert \cdot
   \Vert y \Vert} = \sup_{\Vert x \Vert = 1, \Vert y \Vert = 1} \vert h(x,
   y)\vert$. That is, $\vert h(x, y) \vert \le \Vert h \Vert \cdot \Vert x \Vert
   \cdot \Vert y \Vert$.

   We can now extend the representation theorem to sesquilinear forms.
** Theorem
   Given a bounded sesquilinear form, $h \colon H_1 \times H_2 \rightarrow K$
   ($K$ is a field here), for two Hilbert spaces $H_1$ and $H_2$, then $h$ has a
   representation $h(x, y) = \langle S x, y \rangle$, where $S$ is uniquely
   defined linear operator with $\Vert S \Vert = \Vert h \Vert$.
*** Proof
    For $x$ fixed, $\overline{h(x, y)}$ is a linear functional (complex
    conjugate is required, otherwise, it would only be semi-linear in $y$.)

    Using the representation theorem, there exits a vector $z$ such that, we can
    write the linear functional in the form $\overline{h(x, y)} = \langle y, z
    \rangle$, now $h(x, y) = \overline{\langle y, z \rangle} = \langle z,
    y\rangle$ Here $x$ was fixed.

    If $x$ is not fixed, then $z$ depends on $x$ and define the operator $S$ by
    $Sx = z$, i.e., $h(x, h) = \langle Sx, y \rangle$.

    Now, we need to prove that $S$ is linear, is uniquely defined and is also
    bounded.

    The linearity of $S$ follows from the definition since $\langle S(ax_1 +
    bx_2), y \rangle = h(ax_1 + bx_2, y)$ and $h$ is linear in the first
    argument.

    Boundedness of $S$, $\Vert S \Vert = \sup_{x \neq 0} \frac{\Vert S x
    \Vert}{\Vert x \Vert} = \sup_{x \neq 0} \frac{\langle Sx,
    Sx\rangle^{1/2}}{\Vert x \Vert} = \sup_{x\neq 0, Sx \neq 0} \frac{\langle
    Sx, Sx \rangle}{\Vert x \Vert \cdot \Vert S x \Vert} \le \sup_{x \neq 0, y
    \neq 0} \frac{\vert \langle Sx, y \rangle \vert}{\Vert x \Vert \cdot \Vert y
    \Vert} = \sup_{x \neq 0, y \neq 0} \frac{\vert h(x, y)\vert}{\Vert y \Vert}
    = \Vert h \Vert$. Thus $\Vert S \Vert \le \Vert h \Vert$.

    $\Vert h \Vert = \sup_{x \neq 0, y \neq 0} \frac{h(x, h)}{\Vert x \Vert
    \cdot \Vert y \Vert} = \sup\frac{\Vert Sx, y \rangle}{\Vert x \Vert \Vert y
    \Vert} \le \sup \frac{\Vert Sx \Vert \cdot \Vert y \Vert}{\Vert x \Vert
    \cdot \Vert y \Vert} = \Vert S \Vert$.

    It follows that $\Vert S \Vert = \Vert h \Vert$.
    
    The uniqueness of $S$: Assume that there are two functions $S$ and $T$ with
    the same properties, then $\langle (S - T) x, y \rangle = 0$ for all $x, y$.
    This means that $S = T$.
** Definition
   Given two Hilbert spaces $H_1$ and $H_2$ and a bounded linear operator $T
   \colon H_1 \rightarrow H-2$, then adjoint operator, denoted by $T^{*}$ is
   defined by $\langle Tx, y\rangle = \langle x, T^{*}y \rangle$ for all $x \in
   H_1, y \in H_2$

   We need to show that the operator is really defined. But then we can use the
   previous theorem to show this.
** Theorem
   The operator $T^{*}$ exists and is unique. Furthermore, $\Vert T^{*}\Vert =
   \Vert T \Vert$.
*** Proof
    We define a sesquilinear form by $h(y, x) = \langle y, Tx\rangle$, then
    inner product is sesquilinear and $T$ is linear. Conjugate linearity can be
    seen as follows: $h(y, ax_1 + bx_2) = \langle y, T(ax_1+bx_2) \rangle =
    \langle y, aTx_2 + bTx_2 \rangle = \bar{a}\langle y, Tx_1\rangle +
    \bar{y}\langle y, Tx_2 \rangle = \bar{a}h(y, x_1) + \bar{y}h(y, x_2)$.
    
    Also, $\vert h(x, y) \vert = \vert \langle y, Tx \rangle \vert \le \Vert y
    \Vert \cdot \Vert Tx \Vert \le \Vert T \Vert \cdot \Vert x \Vert \cdot \Vert
    y\Vert$.

    Thus, $\Vert h \Vert \le \Vert T \Vert$. Now we will show that $\Vert T
    \Vert \le \Vert h\Vert$.

    On the other hand, $\Vert h \Vert = \sup_{x \neq 0, y \neq 0} \frac{\vert
    \langle y, Tx \rangle\vert}{\Vert y \Vert \cdot \Vert x \Vert} \ge \sup_{x
    \neq 0, Tx \neq 0} \frac{\langle Tx, Tx \rangle}{\Vert Tx \Vert \cdot \Vert
    Tx \Vert \Vert x \Vert} = \Vert T \Vert$.

    It follows that $\Vert h \Vert = \Vert T \Vert$.

    Now we can use the representation theorem for sesquilinear forms: there
    exits $S$ such that $h(y, x) = \langle Sy, x \rangle$ and we define $T^{*} =
    S$. Thus, $T^{*}$ is bounded and uniquely defined.

    It holds that $\Vert T^{*}\Vert = \Vert S \Vert = \Vert h \Vert$ and $\Vert
    h \Vert = \Vert T \Vert$. Together, $\Vert T^{*} = \Vert T \Vert$ as
    claimed. We also need to show that this satisfies the definition of the
    adjoint operator before.

    We need to show that $h(y, x) = \langle y , Tx\rangle$ and $h(y, x) =
    \langle T^{*}y, x \rangle$. Now $\langle x, T^{*}y \rangle =
    \overline{\langle T^{*}y, x\rangle = \overline{\langle y, Tx \rangle} =
    \langle Tx, y \rangle$ so that $T^{*}$ has the properties we were looking
    for $t$.
** Examples of Adjoint operators
*** Example 1
    Let $A \in \R^{n \times n}$, define $T \colon \R^n \rightarrow \R^n$ by $Tx
    = Ax$. The adjoint operator satisfies $\langle Tx, y \rangle = \langle x,
    T^{*}y\rangle$, i.e., $\langle Tx, y\rangle = \langle Ax, y \rangle =
    (Ax)^ty = x^t A^{t}y = x^{t} (A^{t}y) = \langle x, T^{*} y \rangle$.

    That is, the adjoint operator is given by the transposed matrix $A^{T}$ or
    $A^{H}$ if $A \in \C^{m \times n}$.
*** Example 2
    Let $X \subset \R^d$ and $p_\tau\colon X \times X \rightarrow \R$ be the
    transition density function associated with the stochastic process
    $\{X_t\}_t$. That is, $p_\tau(x, y)$ is the probability that the process
    starting in $x$ goes to $y$ in time $\tau$. We define two operators and
    assume that they are well defined on $L^2$.

    $(P_\tau) p(x) = \int_X p_\tau(y, x) p(y) dy$. (Perjon-Frobenius operator)

    $(K_\tau f)(x) = \int p_\tau(x, y) f(y) dy$. (Koopman operator.)

    Now, we want to show that $p_\tau$ and $K_\tau$ are adjoint with respect to
    $\langle f ,g \rangle = \int f(x)g(x) dx$.
*** Example 3
    For any $x \in \R^n$, define $T$ by $T(x_1, \cdots, x_n) = (0, x_1, \cdots,
    x_{n-1})$, i.e., right-shift operator. Now we want to find the adjoint
    $T^{*}$.

    The adjoint operator is the left shift operator. (One can see this by
    representing $T$ as a matrix, now use the fact that the adjoint of a matrix
    is the transpose.)

    $T^{*}(x_1, \cdots, x_n) = (x_2,\cdots, x_n, 0)$ (the left shift operator)
*** Example 5 (Adjoint operator does not exist)
    The adjoint operator does not always exist. Consider the space of all real
    valued polynomials along with the inner product $\langle f, g \rangle =
    \int_0^1 f(x) g(x)\ dx$. Define the operator $T = \frac{d}{dx}$ to be the
    differentiation operator. Recall that $\frac{d}{dx}$ is not bounded. We only
    showed that it exist for bounded.

    $\langle f, T^{*} g\rangle = \langle Tf, t \rangle = \int_0^1 f'(x)g(x)\ dx
    = [fg]_0^1 - \int_0^1 f(x)g'(x)\ dx = [fg](1) - [fg](0) - \langle f,
    Tg\rangle$ (integration by parts.) Thus $\langle f, (T^{*} + T) g \rangle =
    (fg)(1) - (fg)(0)$. We now define a function $f$ with $f(0) = f(1) = 0$.
* Lecture 18 <2018-12-18 Tue>
** Continuation on the example
   $\langle f, (T^{*} + T)g \rangle = (fg)(1) - (fg)(0), f(x) = x^2(1-x^2)p(x)$.

   $0 = \langle f, (T^{*} + T)g\rangle = \int_{0}^{1} x^2 (1-x^2)[(T +
   T^{*})g](x)\ dx = \langle x^2(1-x^2)(T + T^{*})g, p\rangle$

   Since the integral must be zero for all $p$, it follows that $x^2(1-x^2)[(T +
   T^{*})g](x) = 0$. The term $x^2(1-x^2)$ is positive for all $x \in (0, 1)$
   and only zero for $x=0$ and $x=1$. Thus $(T + T^{*})g$ must be zero for all
   $g$. This implies that $T + T^{*} = 0$ and as a consequence $\lange f, (T +
   T^{*})g \rangle = 0$.

   However, $\langle f, (T + T^{*}) g \rangle = (fg)(1) - (fg)(0)$ which is
   certainly not $0$ for all $f$ and $g$, thus $T^{*}$ cannot exist.
** Lemma
   Given two inner product spaces $X$ and $Y$ and a bounded linear operator $Q
   \colon X \rightarrow Y$

   1. $Q = 0 \iff \langle Qx, y \rangle  = 0 \forall x \in X, \forall y \in Y$
   2. If $X$ is complex and $Q \colon X \rightarrow X$ with $\langle Qx, x
      \rangle = 0, \forall x \in X$ then $Q = 0$.
*** Proof
    The first part is easy. We'll show the second part.

    $0 = \langle Q(ax_1, x_2), ax_1, x_2 \rangle = \vert a\vert^2 \langle Q x_1,
    x_1 \rangle + a \langle Qx_1, x_2\rangle + \bar{a} \langle Q x_2, x_1
    \rangle + \langle Q x_2, x_2\rangle$.

    For $a = 1$, we obtain that $\langle Q x_1, x_2 \rangle + \langle Q x_2, x_1
    \rangle = 0$.

    For $a = i$, we obtain $\langle Q x_1, x_2 \rangle - \langle Qx_2, x_1
    \rangle = 0$.

    The above two equations imply that $\langle Qx_1, x_2 \rangle = 0$ for all
    $x_1, x_2$.

    The property 2, does in general *not hold for real inner product* spaces.
    Define $Q \colon x \mapsto A x$, where $A$ is the following matrix

    | 0 | -1 |
    | 1 | 0  |

    For $x = (x_1, x_2)^T$, $Qx = (-x2, x_1)^T$ and $\langle Qx, x \rangle =
    -x_1 x_2 + x_2 x_1 = 0, \forall x \in X$, but $Q \neq 0$.
    
    The adjoint operator has the following properties:

    1. $\langle T^{*} y, x \rangle = \langle y, Tx\rangle$, we can just see this
       by applying complex conjugate.
    2. $(S + T)^{*} = S^{*} + T^{*}$ (use definition of adjointness and
       linearity of inner product.)
    3. $T^{**} = T$ since $\langle T^{**}x, s\rangle = \langle x, T^{*} y\rangle
       = \langle Tx, y \rangle$. Thus $\langle (T^{**} - T)x, y \rangle = 0$ for
       all $x, y$. From the previous lemma (part 1), we have that $T^{**} - T = 0$.
    4. $(aT)^{*} = \bar{a}T^{*}$ since $\langle (aT)^{*}x, y \rangle = \langle
       x, a Ty \rangle = \bar{a} \langle x, Tx\rangle = \bar{a}\langle T^{*}x, y
       \rangle = \langle \bar{a}T^{*}x, y \rangle$ Thus, $\langle [(aT)^* -
       \bar{a}T^{*}]x, y\rangle = 0$, $\forall x, y$, use argument from (3).
    5. If well-defined, i.e., $T \colon H_1 \rightarrow H_2$ $S \colon H_2
       \rightarrow H_3$: $(ST)^{*} = T^{*}S^{*}$ since $\langle x, (ST)^{*}y
       \rangle = \langle S(Tx), y \rangle = \langle Tx, S^{*}y\rangle = \langle
       x, T^{*}S^{*} y \rangle$
    6. $\Vert S S^{*} \Vert = \Vert S^{*} S \Vert = \Vert S \Vert^2$.
** Definition (unitary)
   Let $T \colon H_1 \rightarrow H_2$ be a bounded linear operator
   
   1. $T$ is called unitary if $T$ is invertible and $T T^{*} = Id_{H_2}$ and
      $T^{*}T = Id_{H_2}$. [fn:15]
   2. For $H_1 = H_2$, $T$ is called self-adjoint if $T = T^{*}$ [fn:16]
   3. For $H_1 = H_2$, then $T$ is called normal if $T^{*}T = TT^{*}$.

   unitary: $\langle T^{*}Tx, y \rangle = \langle x, y \rangle$ by definition.
   The length is preserved. Similar to linear algebra idea that length is preserved.

   Self-adjoint: $\langle Tx, y \rangle = \langle x, T^{**}y \rangle = \langle
   x, Ty \rangle$.

   Normal: $\langle Tx, Ty \rangle = \langle T^{*}Tx, y \rangle = \langle
   TT^{*}x, y \rangle = \langle T^{*}x, T^{*}y\rangle$

   Self-adjoint operators are obviously normal.
** Example
   From a previous example, we know that for $T \colon x \rightarrrow Ax$ for a
   matrix $A \in \R^{n\times m}$, the adjoint is given by $T^{*} \colon y
   \rightarrrow A^{T}y$.

   Thus self-adjointness means $A^{T} = A$ and $A$ must be symmetric. Unitary
   means $A^{T}A = I_n$ thus $m=n$ and $A$ must be orthogonal (unitary if $A$ is
   complex).

   The operator is normal if the matrix $A$ is normal, i..e, $A^{T}A = AA^{T}$.
** Example
   Let us consider the Peran-Frobenius and Koopman operator from a previous
   example again. A system is said to be reversible if the detailed balance
   condition is fulfilled.

   $\pi(x) p_\tau(x, y) = \pi(y) p_\tau(y, x) \forall x, y \in X$.

   Thus $\pi$ is an eigen function of $P_\tau$ with corresponding eigenvalue
   $l=1$.

   $P_\tau$ is self-adjoint with respect to $\langle \cdot, \cdot \rangle_{\pi -
   1}$ This can be seen as follows:

   $$\langle P_\tau f, g \rangle_{\pi^{-1}} = \int\int p_\tau(y, x)\ dx$$

   More calculations follow and we'll get the result.
** Example
   Suppose $A \in \C^{n \times n}$ is a self-adjoint matrix, i.e., $A = A^{*}$.
   Define $u = e^{iA} = \sum_{h=0}^{\infty} (iA)^n/{h!}$. Since for any $B \in
   \C^{n\times n}$: $(B^n)^{*} = (B^{*})^n$ and $(iA)^{*} = TA^{*} = -iA^{*} =
   -iA$ and thus $((iA)^{1/2})^{*} = ((iA)^{*})^{1/2} = (-iA)^n$. We obtain

   $u^{*} = \sum_{h=0}^{\infty} (-iA)^n/{h!} = e^{-iA}$. If two matrices $X$ and
   $Y$ commute, i.e., $XY = YX$, then $e^xe^y = e^{x+y}$.

   As $iA$ and $-iA$ commute, it holds that $e^{iA}e^{-iA} = I$. As a result,
   $U$ is unitary.
** Example
   For a function $f \in L^1(\mathbb{R}) \cap L^2(\R)$, we define the Fourier
   transform as follows:

   $F(\omega) = (\mathscr{F} f)(\omega) = \frac{1}{\sqrt{2\pi}}(\omega) =
   \frac{1}{\sqrt{2\pi}} \int_{-\infty}^\infty e^{-i\omega x} f(x)\ dx$ Here
   $\mathscr{F}$ is the Fourier transformation operator.

   The inverse is given by $f(x) = (\mathscr{F}^{-1} F)(x) =
   \frac{1}{\sqrt{2\pi}} \int_{-\infty}^\infty e^{i\omega x} F(\omega)\
   d\omega$.

   We then obtain $\langle \mathscr{F} f, \mathscr F g \rangle = \langle F,
   G\rangle = \langle f, g \rangle$ (Plancharel's theorem) and $\mathscr{F}$ is
   a unitary operator. For $f = g$, this results in $\Vert f \Vert = \Vert F
   \Vert$.

   (Compare this with Paiseval's identity, which can be viewed as a discrete
   version of this result. The identity says that the norm of the function is
   same as the $l_2$ norm of the coefficients. The above result says something
   similar.)
* Lecture 19 <2018-12-20 Thu> 
** Planchevel's theorem
   $\langle F, G \rangle = \langle f, g \rangle$

   To prove Plancherel's theorem, we write $f(x) = \frac{1}{\sqrt{2\pi}}
   \int_{-\infty}^{\infty} F(\omega) e^{i\omega x}\ d\omega$ and use the
   definition of the Fourier transform

   $$f(x) = \frac{1}{2\pi} \int_{-\infty}^{\infty} \int_{-\infty}^{\infty} f(s)
   e^{-i\omega s}\ ds e^{i\omega x}\ d\omega$$

   Then $\langle f, g \rangle = \int_{-\infty}^{\infty}[\frac{1}{2\pi}
   \int_{-\infty}^{\infty} \int_{-\infty}^{\infty} f(s) e^{-i\omega s}\ ds
   e^{i\omega x} dx \overline{g(x)}\ dx$

   This is equal to $-\int_{-\infty}^{\infty}\left [\frac{1}{\sqrt{2\pi}
   \int_{-\infty}^{\infty} f(s) e^{-i\omega s}\ ds\right ]\left[
   \frac{1}{\sqrt{2\pi}} \int_{-\infty}^{\infty} \overline{g(x)} e^{i\omega x}\
   dx\right] \ d\omega$

   Note that $\overline{\exp{z}} = \exp{\oveline{z}}$ and thus.

   The above thing end up being $\int_{-\infty}^{\infty} F(\omega)
   \overline{G(\omega)}\ d\omega = \langle F, G \rangle$.

   Brief reminder: We used several properties of complex numbers in the last
   examples, e.g., $\overline{z_1 z_2} = \overline{z_1} \cdot \overline{z_2}$
   and $\overline{\exp{z}} = \exp{\overline{z}}$. They can be seen very easily.
** Lemma
   Given a bounded linear operator $T \colon H_1 \rightarrow H_2$, it holds that 

   1. $T$ is an isometry $\iff$
   2. $\langle Tx, Ty\rangle = \langle x, y \rangle$.
*** Proof
    1 to 2.

    Using the polarization identity (related to the Parallelogram law, for $K=
    \R$.)

    We start with $\langle Tx, Ty\rangle = \frac{1}{4}\left( \Vert Tx + Ty
    \Vert^2 - \Vert Tx - Ty\Vert^2\right)$ (this is the polarization identity)

    this can further be written as $\frac{1}{4} \left( \Vert T(x + y)\Vert^2 -
    \Vert T(x - y)\Vert^2\right)$

    Because of the isometry property, we see that this is equal to
    $\frac{1}{4}\left(\Vert x + y \Vert^2 - \Vert x - y \Vert^2) = \langle x, y
    \rangle$.

    Analogously, one can show it for $K= \C$.

    2 to 1.

    $\Vert Tx \Vert^2 = \langle Tx, Tx\rangle = \langle x, x \rangle = \Vert x
    \Vert^2$

    This implies that a length-preserving operator (an isometry) also preserves
    angles.
** Lemma
   For $K = \C$ and a linear $T \colon H \rightarrow H$ it holds that

   1. $T$ is self-adjoint if and only if $\langle Tx, x\rangle \in \R$ for all
      $x \in H$.

   This doesn't make sense in Real valued vector spaces and only make sense in
   Complex valued spaces.
*** Proof
    $\langle Tx, x \rangle = \langle x, Tx\rangle$ (here we are using
    self-adjointness)

    But $\overline{\langle x, Tx\rangle} = \langle Tx, x\rangle$. Thus clearly,
    it is real valued.

    To show the other way around, we use a commonly used trick
    
    First consider $\langle T(x + y), x + y \rangle \in \R$

    Now we use the linearity of the inner product $\langle Tx , x \rangle +
    \langle Tx , y \rangle + \langle Ty, x\rangle + \langle Ty, y\rangle$.

    Two terms on the right is in $\R$ by definition (the left most and the right
    most.)

    If we compute the complex conjugate, we obtain: $\langle T(x + y), x +
    y\rangle = \langle Tx, x\rangle + \langle y, Tx\rangle + \langle x,
    Ty\rangle + \langle Ty, y\rangle$.

    Hence, $\langle Tx, y\rangle + \langle Ty, x \rangle = \langle y,
    Tx\rangle + \langle x, Ty\rangle$

    Now we'll use the same thing for linear combination with $i$ included.

    Similarly $\langle T(x - iy), x - iy\rangle = \langle Tx, x\rangle + \langle
    -iTy, x\rangle + \langle Tx, -iy\rangle + \langle -iTy, -iy\rangle$

    This is equal to $\langle Tx, x \rnagle - i \langle Ty, x \rangle + i\langle
    Tx, y \rangle + \langle Ty, y\rangle$.

    Complex conjugate and subtraction of the two equations results in: $\langle
    Tx, y \rangle + \langle Ty, x\rangle = - \langle y, Tx\rangle + \langle x,
    Ty\rangle$

    We have something similar before,

    Add the equations to get $\langle Tx, y\langle = \langle x, Ty\rangle$,
    which is what we wanted to show.
** Theorem
   If a bounded linear operator is self-adjoint, then $\Vert T \Vert =
   \sup_{\Vert x \Vert \le 1} \vert \langle Tx, x \rangle\vert$.
*** Proof
    The proof again uses the Parallelogram law.

    $\vert \langle Tx, x \rangle \vert \le \Vert Tx \Vert \Vert x \Vert \le
    \Vert T \Vert \cdot \Vert x \Vert^2$. Thus $\Vert T \Vert \ge \sup_{\Vert x
    \Vert \le 1} \Vert \langle Tx, x \rangle \vert$.

    On the other hand, define $M = \sup_{\Vert x \Vert \le 1} \vert \langle Tx,
    x\rangle \vert$.

    $\langle T(x + y), x + y\rangle - \langle T(x - y), x-y\rangle = \langle Tx,
    x\rangle + \langle Tx, y \rangle + \langle Ty, x \rangle + \langle Ty,
    y\rangle - [\langle \langle Tx, x\rangle - \langle Tx, y\rangle - \langle
    Ty, x\rangle + \langle Ty, y\rangle]$.

    This is equal to $\langle Tx, y \rangle + \langle Ty, x \rangle + \langle
    Tx, y\rangle + \langle Ty, x \rangle = \langle Tx, y\rangle +
    \overline{\langle Tx, y\rangle} + \langle Tx, y\rangle + \overline{\langle
    Tx, y\rangle} = 4 \operatorname{Re} \langle Tx, y\rangle$

    $\vert 4 \operatorname{Re} \langle Tx, y \rangle \vert \le \Vert \langle
    T(x + y), x+y\rangle \vert + \vert \langle T(x-y), x-y\rangle \vert \le M
    \cdot \left(\Vert x + y \Vert^2 + \Vert x- y \Vert^2\right) = 2 M(\Vert x
    \Vert^2 + \Vert y \Vert^2)$ This uses parallelogram law.

    Note that for arbitrary $z \colon \vert \langle Tz, z\rangle \vert = \Vert
    z\Vert^2 \langle T \frac{z}{\Vert z}, \frac{z}{\Vert z\Vert}\rangle \le
    \Vert z \Vert^2 \cdot M$

    For $\Vert x \Vert \le 1$ and $\Vert y \Vert \le 1$: $\Vert
    \operatorname{Re} \langle Tx, y \rangle \vert \le M$. Set $y =
    \frac{Tx}{\Vert Tx\vert}$. Set $y = \frac{Tx}{\Vert Tx \Vert}$, then $\vert
    \operatorname{Re} \langle Tx, \frac{Tx}{\Vert Tx\Vert}\vert = \Vert Tx \Vert
    \le M$
* Lecture 20 <2019-01-08 Tue>
  We finished Metric space, Banach spaces etc.
** Reproducing Kernel Hilbert spaces
*** Kernels and their properties
    We will consider similarity measures of the form $k \colon X \times X
    \rightarrow \R$, where $X$ is a non-empty set.
*** Definition
    A function $k \colon X times X \rightarrow \R$ is called kernel if there
    exists a real Hilbert space $H$ and a map $\phi \colon X \rightarrow H$ such
    that for all $x, x' \in X$, we know that $k(x, x') = \langle \phi(x),
    \phi(x') \rangle_H$.

    We call $\phi$ feature map and $H$, the feature space of $k$.
*** Example
    A particularly simple similarity measure on $\R^n$ is the standard inner
    product on $\R^n$. $k(x, x') = \langle x, x'\rangle = x^T x' = \sum x_i
    x_i'$. Why is this a similarity measure? If we have two vectors that are
    orthogonal, then the similarity would be zero. Whereas if they are parallel,
    the inner product is closer. [fn:17]

    Let $x$ and $x'$ be vectors of unit length, then $k(x, x') = 1$ if $x = x'$
    (high similarity) and $h(x, x') = 0$ if $x \perp x'$ (low similarity).
*** Lemma
    Let $X$ be as above and $f_n \colon X \righarrow \R$ and $n \in \N$ be
    functions such that $(f_n(x))_n\in l_2$ for all $x\in X$. Then $k(x, x') =
    \sum_{n = 1}^{\infty} f_n(x) f_n(x')$ defines a kernel.
**** Proof
     Holder's inequality yields that $\sum_{n=1}^{\infty} \vert f_n(x)
     f_n(x')\vert \le \Vert (f_n(x_n)) \Vert_{l_2} \cdot \Vert f_n(x')
     \Vert_{l_2}$. 

     Thus, by definition, of $f_n(x)$, the series converges absolutely, which
     means it also converges. Then one can define the Hilbert space to be $l^2$
     and $\phi \colon X\righarrow H$ by $\phi(x) = (f_n(x))_n$, then $k(x, x') =
     \langle \phi(x), \phi(x')\rangle_H$ and defines a kernel. This completes
     the proof
*** Remark
    Almost all kernels have such a representation which can be constructed
    explicitly (Mercer feature space will be introduced later)

    Kernel based methods and reproducing kernel Hilbert spaces are often in
    machine learning. Let us consider a simple classification problem.
*** Example
    Assume that we have two classes of objects (e.g., sick/healthy) We are then
    given a new object and we have to assign it to one of the two classes.

    Mathematically, we can formalize this as follows: Give training data $x_1,
    \cdots, x_m$ and labels $y_1, \cdots, y_m$ with $x_i \in X$ and $y_i \in
    \{-1, 1\}$. Here $1$ would means that the person is sick and $-1$, that the
    person is healthy. Find a function $f\colon X \rightarrow \{-1, 1\}$ that
    assigns a new object a label (this is an instance of supervised learning)

    The first idea could be to assign a new data to the class with closer mean:

    $c_{+} = \frac{1}{m_{ +}} \sum_{y_i = 1} x_i$ and $c_{-} = \frac{1}{m_{-}}
    \sum_{y_i = 1} x_i$ where $m_{ +}$ and $m_{-}$ are the number of instances
    of objects with $y_i = 1$ and $y_i = -1$ respectively.

    We now compare the midpoint between $c_{+}$ and $c_{-}$, i.e., $c \colon
    \frac{1}{2}(c_{ +} + c_{-})$, and check whether a new data point $x$
    encloses an angle smaller than $\pi/2$ with the vector, $w = c_{ +} - c_{-}$
    which connects $c_{ +}$ and $c_{-}$.

    If the sign of the cosine of the angle between $x - c$ and $w$ is $1$, we
    assign by $+1$, otherwise to $-1$. Thus $y = \operatorname{sgn}(\langle x -
    c, w \rangle) = \operatorname{sgn}(\langle x - \frac{1}{c_{ +} + c_{-}}, c_{
    +} - c_{-})$, this can be shown to be same as $\operatorname{sgn} (\langle
    x, c_{ +} - \langle x, c_{-}\rangle + b)$ with $b = \frac{1}{2} \left(\Vert
    c_{-1}\Vert^2 - \Vert c_{ +}\Vert^2 \right)$.

    Instead of computing the inner product in the state space, we first
    translate the data using $\phi$ and compute the inner product in feature
    space using the kernel $k$, $y = \operatorname{sgn}[\langle x, \frac{1}{m_{
    +}} \sum_{y_i = 1} x_i \rangle - \langle x, \frac{1}{m_{-}} \sum_{y_i = -1}
    \sum x_i + b]$. This is same as $\operatorname{sgn}[\frac{1}{m_{ +}
    \sum_{y_i = 1} \langle x, x_i \rangle - \frac{1}{m} \sum_{y_i = -1} \langle
    x, x_i \rangle + b]$.

    Kernelization, $y = \operatorname{sgn} [\frac{1}{m^{ +}} \sum_{y_i = 1}
    \langle \phi(x), \phi(x) \rangle - \frac{1}{m_{-}} \sum_{y_i = -1} \langle
    \phi(x), \phi(x_i) \rangle + \tilde{b}]$. Where $b$ is given by $\tilde{b} =
    \frac{1}{2} = \frac{1}{2} [ \frac{1}{m^2} \sum_{y_i = -1, y_j = -1} h(x_i,
    x_j) - \frac{1}{m^2_{ +}} \sum_{y_i = 1, y_j = 1} h(x_i, x_j)$

    This results in a non-linear version of the classification algorithm. Note
    that $\phi(x)$ does not need to be computed explicitly only kernel
    evaluations are required. This is (one aspect of) the so called kernel
    trick.

    If we now choose for instance, $k(x, x') = (1 + \langle x, x'\rangle)^2$
    also, the "circle example" introduced above can be classified.
*** Example
    Let $X = \R^2$ and the kernel $k(x, x') = (1 + \langle x, x'\rangle)^2$. We
    obtain, $k(x, x') = (1 + x_1 x_1' + x_2x_2')^2 = \cdots = 1 + 2x_1x_1' +
    2x_2 x_2' + 2x_n x_1'x_2x_2' + \lambda_1^2 \lambda'_1^2 + \lambda_2^2
    x_2'^2$.

    We can rewrite this as an inner product of two vectors.

    $(1, \sqrt(2)x_1, \sqrt{2}x_2, \sqrt{2}x_1x_2, x_1^2, x_2^2)^t$ and $(1,
    \sqrt{2}x_1', \sqrt{2}x_2', \sqrt{2}x_1'x_2', x_1^2' x_2'^2)^t$. This is
    $\langle \phi(x), \phi'(x)\rangle$.

    The feature space contains all monomials of order up to and including two.
    The inner product in the six dimensional feature space can be computed
    efficiently in the two dimensional state space. In general, for $\R^d$, the
    kernel $k(x, x') = (c + \langle x, x'\rangle)^p$ contains all monomials of
    order up to $p$.
*** Remark
    The feature space representation is not unqiue. That is, we have $h(x, x') =
    \langle \phi_1(x), \phi_1(x')\rangle$ and $h(x, x') = \langle \phi_2(x),
    \phi_2(x')\rangle$, $\phi_1$ and $\phi_2$ might be different 9also the
    associated hilbert spaces might be completely different) This however, does
    in general not matter since the goal is to write algorithms, in terms of
    kernel evaluations.
*** Lemma
    1. Given a kernel $k$, then $\alpha \cdot k$ for $\alpha > 0$ is a kernel.
    2. Given kernels $k_1$ and $k_2$, $k_1 + k_2$ is a kernel.
    3. Also $k_1 \cdot k_2$ is a kernel.
**** Proof
     $k(x, x') = \langle \phi(x), \phi(x') \rangle$, thus $(\alpha k)(x, x') =
     \langle \sqrt{\alpha} \phi(x), \sqrt{\alpha} \phi(x')\rangle$.

     $k_1(x, x') = \lanlge \phi_1(x), \phi_2(x) \rangle$, $k_2(x, x') = \langle
     \phi_2(x), \phi_2(x') \rangle$, define $\phi(x) = (\phi_1(x),
     \phi_2(x))^t$, then, $\langle \phi(x), \phi(x')\rangle = \langle
     [\phi_1(x), \phi_2(x)]^t, [\phi_1(x), \phi_2(x)]^t\rangle = \langle
     \phi_1(x), \phi_1(x') \rangle + \langle \phi_2(x), \phi_2(x') \rangle =
     k_1(x, x') + k_2(x, x')$

     $k_1(x, x')k_2(x, x') = \sum_{i}\phi_1^{i}(x) \phi_n^{i}(x')
     \sum_{j}\phi_2^j(x) \phi_2^j(x') = \sum_{i, j} [\phi_1^i(x)
     \phi_2^j(x)][\phi_1^i(x') \phi_2^j(x')]$

     This can be written as $\langle (\phi_1 \otimes \phi_2)(x), (\phi_1 \otimes
     \phi_2)(x') \rangle$. This is the tensor product of $\phi_1$ and $\phi_2$,
     i.e., $(\phi_1 \otimes \phi_2)_{ij} = \phi_i^{i} \phi_2^{j}$.
* Lecture 21 <2019-01-10 Thu>
** Positive Definite
   Given a Kernel $K$ and data $x_1, \cdots, x_m \in X$, the $m \times m$ matrix
   $G = (g_{ij})$ with $g_{ij} = k(X_i, X_j)$ is called Gram matrix.
** Definition
   A kernel $k \colon X \times X \rightarrow \R$ is called positive definite if
   for all $m$, for all $X_1, \cdots, X_m \in X$, for all $\alpha_1, \cdots,
   \alpha_m$, we have $\sum_{i, j = 1}^{n} \alpha_i\alpha_j k(x_i, x_j) =
   \alpha^T G \alpha \ge 0$ for all vectors $\alpha$.

   Furthermore, $k$ is said to be *strictly positive definite*, if for mutually
   different $X_1, \cdots, X_m$ equality $\alpha^T G \alpha = 0$ holds for
   $\alpha = 0$. (this is an additional condition) The kernel $k$ is called
   *symmetric* if $k(x, x') = k(x', x)$ for all $x, x' \in X$.
** Remark
   What we call positive definite is also sometimes called positive
   semi-definite and what we call strictly positive definite is called positive
   definite.
** Property
   A symmetric matrix $G$ is positive definite if and only if eigenvalues are
   non-negative. We're talking about Real, meaning that the Eigenvalues are
   positive.
** Remark
   The term kernel dates back to analysis of integral operators of the form
   $(T_k f)(x) = \int k(x, x') f(x') dx'$.
** Lemma (Cauchy-Schwarz for kernels)
   If $k$ is symmetric and positive definite (in short, s.p.d in what follows)
   then $k(x_1, x_2)^2 \le k(x_1, x_2)k(x_2, x_2)$
*** Proof
    Consider the Gram Matrix $G=$
    
    | $k(x_1, x_2)$ | $k(x_1, x_2)$ |
    | $k(x_2, x_1)$ | $k(x_2, x_2)$ |
    
    Which is by definition s.p.d. Remember that the product of all eigenvalues
    is equal to the determinant of the matrix. We now know that all the
    eigenvalues are non-negative, which means that the determinant is
    non-negative.

    The determinant is $k(x_1, x_2)k(x_2, x_2) - k(x_1, x_2)^2 \ge 0$. Thus we
    have the theorem.
** The reproducing kernel map
   Let $k$ be a s.p.d kernel and $X$ a non-empty set.
** Definition (Canonical feature map)
   Let $\R^X = \{ f\colon X \rightarrow \R \}$ denote the set of all functions
   from $X$ to $\R$. We define $\phi \colon X \rightarrow \R^X$ by $x\mapsto
   k(\cdot, x)$. (Note that we assign each point in $X$ a function.)

   Thus, $\phi(x)(x') = k(x', x) = k(x, x')$ We can now define functions by
   $f(\cdot) = \sum \alpha_i [\phi(x_i)](\cdot) = \sum_{i = 1}^{n} \alpha_i
   k(\cdot, x_i)$ for $m \in \N$, $\alpha_i \in \R$ and $x_1, \cdots, x_m \in
   X$.

   Given two functions $f = \sum_{i=1}^{m} \alpha_i k(\cdot, x_i)$ and $g =
   \sum_{j = 1}^{m'} \beta_j k(\cdot, x_j')$ we define an inner product by
   $\langle f, g \rangle = \sum_{i=1}^{m} \sum_{j = 1}^{m'} \alpha_i \beta_j
   k(x_i, x_j')$
** Lemma
   This new inner product $\langle \cdot, \cdot \rangle$ itself defines s.p.d
   kernel.
*** Proof
    Symmetry follows from the symmetry of the $k$. We have to show that for
    arbitrary function $f_1, \cdots, f_m$ and coefficients $\alpha_1, \cdots,
    \alhpa_m$, $\sum_{i, j} \alpha_i \alpha_j \langle f_i, f_j \rangle = \langle
    \sum_{i} \alpha_i f_i, \sum_{j} \alpha_j f_j \rangle = \langle f,
    \tilde{f}\rangle$

    Let $\tilde{f}$ be within $\tilde{f} = \sum_{i = 1}^{m^2} \tilde{\alpha}_i
    k(\cdot, \tilde{x}_i)$, then $\langle \tilde{f}, \tilde{f}\rangle = \sum_{i,
    j} \tilde{\alpha}_i \tilde{\alpha}_i k(\tilde{x}_i, \tilde{x}_j) \ge 0$,
    since $k$ is pd. This completes the proof?

    Given $f = \sum_{i = 1}^{n} \alpha_i k(\cdot, x_i)$, we obtain $\langle f,
    k(\cdot, x) \rangle = \sum_{i=1}^{n} \alpha_i k(x, x_i) = f(x)$

    This is called the reproducing property. Thus, function evaluations can now
    be interpreted as inner products in an inner product space. In particular,
    we obtain $\langle k(\cdot, x), k(\cdot, x') \rangle = k(x, x')$ Since we
    defined $\phi(x) = k(\cdot, x)$, this yields, $\langle \phi(x), \phi(x')
    \rangle = k(x, x')$.

    This derivation showed that we can construct a feature map $\phi$ given a
    kernel $k$. Similarly, a feature map, defines as s.p.d. kernel, via $k(x,
    x') = \langle \phi(x), \phi(x') \rangle$ since $\sum_{i, j} \alpha_i
    \alpha_j(x_i, x_j) = \langle \sum_{i} \alpha_i \phi(x_i),
    \sum\alpha_j\phi(x_j)\rangle = \Vert \sum \alpha_i \phi(x_i) \Vert^2 \ge 0$.
** The reproducing kernel Hilbert space
   The space of functions given by $f = \sum_{i = 1}^{m} \alpha_i k(\cdot, x_i)$
   along with the inner product $\langle \cdot, \cdot \rangle$ defines an inner
   product space or pre-Hilbert space. We can now complete this space by adding
   limit points of sequences that converge in the norm $\Vert \cdot \Vert =
   \langle \cdot, \cdot \rangle^{1/2}$ induced by the inner product.

   1. $\langle f, h(\cdot, x)\rangle = f(x)$ for $f\in H$.
   2. $H = \operatorname{span}\{k(\cdot, x) \vert x\in X\}$

   There are equivalent definitions using evaluation functionals $\delta_x f =
   f(x)$ see Stienward/Christmann (Support Vector Machines.)
** Lemma
   The RKHS uniquely determines the reproducing kernel $k$
*** Proof
    Assume $k_1$ and $k_2$ are reproducing kernels, then $\langle h_1(\cdot, x),
    k(\cdot, x') \rangle$ The reproducing property of Kernel $k_2$.

    We may now swap the two arguments, $\langle k_2(\cdot, x'), k_1(\cdot, x)
    \rangle = k_2(x', x) = k_2(x, x')$
** Mercer Feature space
   It is possible to derive an explicit representation of the feature space
   where features are (possibly infinite-dimensional) vectors (unlike the
   canonical feature map, where we assign functions to all $x \in X$.) The
   resulting Mercer representation is helpful for understanding RKHS.

   Let $X$ be compact and $K$ a continuous kernel in what follows:.
** Definition
   Given a kernel $K$, the integral operator $S_k \colon L_2(\mu) \rightarrow H$
   is defined by the operator $S_k f(x) = \int h(x, x') f(x') d \mu(X')$ and
   $T_k(\mu) \rightarrow L_2(\mu)$ by $T_k = S_k^{*} S_k$.

   If you are not familiar with measures think of $d \mu(x')$ as $dx'$, i.e.,
   the standard Lebesgue measure.
* Homeworks
** Homework 8
*** 8.1
    A subset $M$ of a vector space is said to be convex if for two points $m_1,
    m_2$ in $M$, the line segment joining $m_1$ and $m_2$ lies in $M$, i.e.,
    $\lambda m_1 + (1-\lambda)m_2 \in M$.

    Given $n$ vectors $x_1, \cdots, x_n\in M$ and $\alpha_i \in K$ such that
    $\sum_1^n \alpha_i = 1$, we need to show that $\sum_1^n \alpha_i x_i \in M$.

    We'll prove this by induction on $n$.

    The base case $n=1$ is trivially true, since the only case is $\alpha_1 = 1$
    and $1\cdot x_1 \in M$. Now we assume that the statement is true for $n-1$
    vectors.

    The sum $\alpha_1x_1 + \cdots + \alpha_{n-1}x_{n-1} + \alpha_nx_n=
    (\sum_1^{n-1}\alpha_i)(\lambda\alpha_1 x_1 + \cdots +
    \lambda\alpha{n-1}x_{n-1}) + \alpha_n x_n$. Where $\lambda =
    \frac{1}{\sum_1^{n-1} \alpha_i}$. Notice that $\sum_1^{n-1} \lambda_i
    \alpha_i = 1$, thus we can use the inductive hypothesis to see that
    $\lambda\alpha_1 x_1 + \cdots + \lambda\alpha{n-1}x_{n-1} = y \in M$. Now,
    $(\sum_1^{n-1}\alpha_i)y + \alpha_n x_n \in M$ by convexity, since
    $\sum_1^{n-1}\alpha_i + \alpha_n = 1$.
    
    Hence by induction, the statement is true for all values of $n$.
*** 8.2
    If $y \in M$ and $x - y \in M^{\perp}$, then $\langle x - y, y \rangle = 0
    \iff \langle x, y \rangle = \langle y, y \rangle$.

    From 1, we know that $y = P_Mx$ if and only if $y \in M$ and $x - y \in
    M^\perp$,

    Let $a = P_M x$ and $b = P_m y$, then $a, b \in M$ and $x-a, y-b \in
    M^\perp$.

    $$\langle P_M x, y \rangle = \langle a, y \rangle = \langle a, y \rangle - \langle a, y - b \rangle =
    \langle a, b\rangle$$

    Similarly

    $$\langle x, P_M y \rangle = \langle b, x \rangle = \langle b, x \rangle - \langle b, x - a \rangle =
    \langle a, b\rangle$$

    Thus $\langle a, b \rangle = \langle P_M x, y \rangle = \langle x, P_M y
    \rangle = \langle a, b\rangle$.
* Footnotes

[fn:17] The notion of similarity measure is not precise.

[fn:16] In linear algebra, the equivalence is symmetric.

[fn:15] The equivalent property in linear algebra is orthogonality.

[fn:14] All the details were not proven. Just a detour.

[fn:13] In general projection need not be linear, but here it is linear.

[fn:12] This is similar to the theorem we did in Discrete Geometry 1

[fn:11] Apparently the $1$ norm cannot be induced by an inner product. There is
something more going on here. That's because the statement is only true if
$\langle x, x \rangle = \Vert x \Vert^2$, i.e., the space should already be
induced by an inner product. This is not true in the first place for $l^1$ norm.

[fn:10] We didn't prove this.

[fn:9] Idea of machine learning. We have two sets of points, we need to find a
function (often linear) that separates the points. But it may not be easy. So
one idea is to find a linear function to a higher dimensional space and then one
may be able to separate the points in the higher dimensional space.

[fn:8] These are called Kernels. But kernels in Machine learning is $k(x, y)
=\langle \phi(x), \phi(y)\rangle$, for example $h(x, y) = \exp(-\Vert x -
y\Vert/\varepsilon$ is called a Gaussian kernel. Another example is $h(x, y) =
(1+\langle x, y\rangle)^p$ polynomial kernel

[fn:7] This is an unbounded operator. We still haven't defined what bounded
operators are, though.

[fn:6] We might not need this property. 

[fn:5] The proof wasn't done in the class. But the idea is the all Cauchy
sequences converges.

[fn:4] This might be needed for the next exercises.

[fn:3] Is compactness needed?

[fn:2] Look up at proofs of this fact

[fn:1] A14 1126 tutorial
 
